title: Cronx

# Include external resources
# resources:
#   - url: !resource vertical-stack-in-card/vertical-stack-in-card.js
#     type: js
resources:
  - url: !resource custom/bignumber-card.js
    type: js
  - url: !resource custom/mini-media-player-bundle.js
    type: module
  - url: !resource custom/fold-entity-row.js
    type: js
  - url: !resource custom/mini-graph-card-bundle.js
    type: js
# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router

views:
    # View tab title.
  - !include home/view_home.yaml
  - !include pulse/view_pulse.yaml
  - !include media/view_media.yaml
  - !include transport/view_transport.yaml
  - !include settings/view_settings.yaml
