title: Cronx

# Include external resources
resources:
  - url: !resource vertical-stack-in-card/vertical-stack-in-card.js
    type: js

# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router

views:
    # View tab title.
  - !include view_home.yaml
  - !include view_pulse.yaml
