title: Cronx

# Include external resources
# resources:
#   - url: !resource vertical-stack-in-card/vertical-stack-in-card.js
#     type: js
resources:
  - url: !file /local/lovelace/card-tools.js
    type: js
  - url: !file /local/lovelace/bignumber-card.js
    type: js
  - url: !file /local/lovelace/mini-media-player-bundle.js
    type: module
  - url: !file /local/lovelace/fold-entity-row.js
    type: js
  - url: !file /local/lovelace/mini-graph-card-bundle.js
    type: module
  - url: !file /local/lovelace/vertical-style-card.js
    type: js
  - url: !file /local/lovelace/compact-custom-header.js
    type: js
  - url: !file /local/lovelace/button-card.js
    type: module
  - url: !file /local/simple-thermostat/simple-thermostat.js
    type: module
# Exclude entities from "Unused entities" view
# excluded_entities:
#   - weblink.router

views:
    # View tab title.
  - !include home/view_home.yaml
  - !include pulse/view_pulse.yaml
  - !include media/view_media.yaml
  - !include transport/view_transport.yaml
  - !include settings/view_settings.yaml
