image:
  homeassistant/home-assistant

stages:
  - test

test:
  stage: test
  script:
    - cd /usr/src/app
    - cp $CI_PROJECT_DIR/ci_secrets.yaml $CI_PROJECT_DIR/secrets.yaml
    - /usr/local/bin/python -m homeassistant --config $CI_PROJECT_DIR/ --script check_config
  artifacts:
    paths:
       - ./*
