# @Author: Will Scott <willscottuk>
# @Date:   25/06/2017 16:16
# @Project: Ambassadr Home Automation
# @Last modified by:   willscottuk
# @Last modified time: 25/06/2017 16:18

language: python
python:
  - "3.4"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
