# @Author: Will Scott <willscott>
# @Date:   18/02/2018 16:49
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 28/02/2018 20:30

alexa:
  filter:
# groups don't currently work correctly in HASS.
    include_entities:
      - light.sofa
      - light.dining
      - light.daniel_side
      - light.will_side
      - light.main
      - light.map
      # only expose the TRADFRI grouped lights
      - light.ensuite
      - light.main_bathroom
      - light.kitchen
      - light.utility
      # only because scripts can't be properly exposed
      - input_boolean.good_night
      - input_boolean.good_morning
    #   - group.living_room
    #   - group.hall
    #   - group.bedroom
    #   - group.map_room
    #   - group.bathroom
    #   - group.utility
    #   - group.kitchen
    #   - group.ensuite
    include_domains:
      - switch
