card_urls:
  - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
  - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
component_urls:
# Released build
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json