# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:46
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 08/02/2018 09:04

javascript_version: es5 # Lots of frontend issues on iOS so reverting back to the old version of javascript.

extra_html_url:
  - /local/custom_ui/state-card-eastbound.html
  - /local/custom_ui/state-card-westbound.html
  - /local/custom_ui/state-card-traintimes.html
  - /local/custom_ui/state-card-custom-ui.html
  - /local/custom_ui/state-card-tiles.html
  - /local/custom_ui/state-card-custom-heating.html
extra_html_url_es5:
  - /local/custom_ui/state-card-eastbound.html
  - /local/custom_ui/state-card-westbound.html
  - /local/custom_ui/state-card-traintimes.html
  - /local/custom_ui/state-card-custom-ui-es5.html
  - /local/custom_ui/state-card-tiles.html
  - /local/custom_ui/state-card-custom-heating.html

themes: !include themes.yaml
