# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:49
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 12/02/2018 21:31

exclude:
  entities:
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_high_temperature
    - group.trams
    - sensor.front_door_access_control
