# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:49
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/01/2018 12:49

exclude:
  entities:
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_high_temperature
