# @Author: Will Scott <willscott>
# @Date:   28/02/2018 18:27
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 15/04/2018 20:20

auto_start: false
filter:
  include_domains:
    - light
