# @Author: Will Scott <willscott>
# @Date:   28/02/2018 18:27
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 15/04/2018 20:37

auto_start: false
filter:
  include_entities:
    # Include the grouped lights
    - light.living_room
    - light.hall
    - light.bedroom
    - light.map_room
    - light.bathroom
    - light.utility
    - light.kitchen
    - light.ensuite
    - sensor.temperature_158d00022b5707
    - sensor.temperature_158d00022b5806
    - sensor.temperature_158d00022b584d
    - sensor.temperature_158d00022cb6b0
    - sensor.temperature_158d00022cbd07
    - sensor.heating_temperature
    - sensor.humidity_158d00022b5707
    - sensor.humidity_158d00022b5806
    - sensor.humidity_158d00022b584d
    - sensor.humidity_158d00022cb6b0
    - sensor.humidity_158d00022cbd07
    - sensor.heating_humidity
