# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:56
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 21/01/2018 09:56

exclude:
  entities:
     - sensor.time
     - automation.plant_update
     - sensor.eastbound_trams
     - sensor.westbound_trams
     - sensor.tram_status
     - group.ambassadr
  domains:
     - light
     - zwave
     - weather
     - zone
