# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:52
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 31/03/2018 07:54

default: error
logs:
  homeassistant.components.homekit: debug
