# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:57
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/01/2018 12:57

broker: !secret mqtt_broker
port: !secret mqtt_port
client_id: home-assistant-1
username: homeassist
password: !secret mqtt_pass
