# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:52
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/01/2018 12:52

purge_interval: 2
purge_keep_days: 4
db_url: !secret db_url
