# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:53
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/01/2018 12:53

# Turn off HASS analytics
reporting: no
