# @Author: Will Scott <willscott>
# @Date:   20/03/2018 20:23
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/03/2018 20:24

discovery_retry: 5
gateways:
  - key: !secret xiaomi
