icon: mdi:settings
# Title of the view. Will be used as the tooltip for tab icon
title: Settings
cards:

  - type: custom:compact-custom-header
    header: true
    notification: true
    menu: true
    voice: false
    options: false
    tabs: true
    clock: notification
    clock_format: 24

    # Entities card will take a list of entities and show their state.
  - type: entities
    title: Modes
    entities:
      - input_boolean.holiday_mode
      - input_boolean.guest_mode
      - input_boolean.romance_mode
      - input_boolean.party_mode
      - input_boolean.quiet_mode
      - input_boolean.film_mode
      - input_boolean.developer_mode

  - type: conditional
    conditions:
      - entity: input_boolean.developer_mode
        state: "on"
    card:
      type: custom:monster-card
      card:
        type: entities
        title: Automations
      filter:
        include:
          - domain: automation
            options:
              secondary_info: last-changed

