# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:34
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 13/11/2017 21:20

# This package deals with what I hope will become whole home audio!


homeassistant:
  customize:
    media_player.snapcast_client_676c68d1dd024661b816a27cea8a6b4c:
      friendly_name: Vox One

media_player:

  - platform: squeezebox
    host: 10.10.1.200
    username: !secret squee_user
    password: !secret squee_pass

  - platform: spotify
    client_id: !secret spot_id
    client_secret: !secret spot_secret

  - platform: snapcast
    host: !secret ip_addr
