# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:34
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 24/06/2018 14:48

# This package deals with what I hope will become whole home audio!
# Lots more work needed here! TODO: Almost everything!

homeassistant:
  customize:
    input_text.dummy_player_lr_one:
      icon: mdi:cast
      custom_ui_state_card: state-card-mini-media-player
      config:
        player: media_player.living_room_one
    input_text.dummy_player_br_one:
      icon: mdi:cast
      custom_ui_state_card: state-card-mini-media-player
      config:
        player: media_player.bedroom_one
    input_text.dummy_player_spotify:
      icon: mdi:cast
      custom_ui_state_card: state-card-mini-media-player
      config:
        player: media_player.spotify
    input_text.audio_tiles_lr:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        entities:
          - entity: script.group_from_lr
            column_span: 2
            label: Group
          - entity: script.sonos_reset
            column_span: 2
            label: Reset
          # Row 2
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Epic"
            label: Epic
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Cinematic Chillout"
            label: Cinematic
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Disney"
            label: Disney
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Emergency Party Mode"
            label: Party
          # Row 3
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "BBC Radio 4"
            label: Radio 4
            column_span: 2
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Current"
            label: Current
            column_span: 2
    input_text.audio_tiles_br:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        entities:
          - entity: script.group_from_br
            column_span: 2
            label: Group
          - entity: script.sonos_reset
            column_span: 2
            label: Reset
          # Row 2
          - entity: script.play_something_somewhere
            data:
              where: "media_player.bedroom_one"
              what: "Epic"
            label: Epic
          - entity: script.play_something_somewhere
            data:
              where: "media_player.bedroom_one"
              what: "Cinematic Chillout"
            label: Cinematic
          - entity: script.play_something_somewhere
            data:
              where: "media_player.bedroom_one"
              what: "Disney"
            label: Disney
          - entity: script.play_something_somewhere
            data:
              where: "media_player.bedroom_one"
              what: "Emergency Party Mode"
            label: Party
          # Row 3
          - entity: script.play_something_somewhere
            data:
              where: "media_player.bedroom_one"
              what: "BBC Radio 4"
            label: Radio 4
            column_span: 2
          - entity: script.play_something_somewhere
            data:
              where: "media_player.bedroom_one"
              what: "Current"
            label: Current
            column_span: 2
    input_text.audio_tiles_off:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        entities:
          - entity: input_boolean.pp_living_room_one
            label: Living Room
          - entity: input_boolean.pp_bedroom_one
            label: Bedroom
          - entity: input_boolean.pp_joined
            label: Group
          - entity: script.sonos_reset
            label: Reset
          # Row 2
          - entity: script.play_something_somewhere
            data_template:
              where: "{{ 'media_player.' ~ states('input_select.primary_player') }}"
              what: "Epic"
            label: Epic
          - entity: script.play_something_somewhere
            data_template:
              where: "{{ 'media_player.' ~ states('input_select.primary_player') }}"
              what: "Cinematic Chillout"
            label: Cinematic
          - entity: script.play_something_somewhere
            data_template:
              where: "{{ 'media_player.' ~ states('input_select.primary_player') }}"
              what: "Disney"
            label: Disney
          - entity: script.play_something_somewhere
            data_template:
              where: "{{ 'media_player.' ~ states('input_select.primary_player') }}"
              what: "Emergency Party Mode"
            label: Party
          # Row 3
          - entity: script.play_something_somewhere
            data_template:
              where: "{{ 'media_player.' ~ states('input_select.primary_player') }}"
              what: "BBC Radio 4"
            label: Radio 4
            column_span: 2
          - entity: script.play_something_somewhere
            data_template:
              where: "{{ 'media_player.' ~ states('input_select.primary_player') }}"
              what: "Current"
            label: Current
            column_span: 2
    input_text.audio_tiles_multi:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        entities:
          - entity: script.group_from_lr
            column_span: 1
            label: "LR -> all"
          - entity: script.group_from_br
            column_span: 1
            label: "BR -> all"
          - entity: script.sonos_reset
            column_span: 2
            label: Reset
    input_text.audio_tiles_joined:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        entities:
          - entity: script.unjoin_sonos
            column_span: 2
            label: Ungroup
          - entity: script.sonos_reset
            column_span: 2
            label: Reset
          # Row 2
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Epic"
            label: Epic
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Cinematic Chillout"
            label: Cinematic
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Disney"
            label: Disney
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Emergency Party Mode"
            label: Party
          # Row 3
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "BBC Radio 4"
            label: Radio 4
            column_span: 2
          - entity: script.play_something_somewhere
            data:
              where: "media_player.living_room_one"
              what: "Current"
            label: Current
            column_span: 2

tts:
  - platform: google
    language: 'en-uk'
  - platform: amazon_polly
    aws_access_key_id: !secret aws_id
    aws_secret_access_key: !secret aws_key
    region_name: 'eu-west-1'
    voice: 'Geraint'

media_player:

  # Squeezebox and snapcast removed, sonos in!

  - platform: spotify
    client_id: !secret spot_id
    client_secret: !secret spot_secret

  - platform: sonos

script:
  sonos_tts:
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: "{{ 'media_player.' ~ where }}"
          with_group: yes
      - service: media_player.sonos_unjoin
        data_template:
          entity_id: "{{ 'media_player.' ~ where }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ 'media_player.' ~ where }}"
          volume_level: 0.3
      - service: tts.amazon_polly_say
        data_template:
          entity_id: "{{ 'media_player.' ~ where }}"
          message: "{{ what }}"
      - delay:
          seconds: 1
      - delay: >-
          {% set duration = states.media_player[where].attributes.media_duration %}
          {% if duration > 0 %}
            {% set duration = duration - 1 %}
          {% endif %}
          {% set seconds = duration % 60 %}
          {% set minutes = (duration / 60)|int % 60 %}
          {% set hours = (duration / 3600)|int %}
          {{ [hours, minutes, seconds]|join(':') }}
      - service: media_player.sonos_restore
        data_template:
          entity_id: "{{ 'media_player.' ~ where }}"
          with_group: yes
      - service: script.stream
        data_template:
          message: "{{'\U0001f4e2 ' ~ where ~': ' ~ what }}"
  sonos_broadcast:
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id:
            - media_player.living_room_one
            - media_player.bedroom_one
          with_group: yes
      - service: media_player.sonos_unjoin
        data_template:
          entity_id:
            - media_player.living_room_one
            - media_player.bedroom_one
      - service: media_player.sonos_join
        data_template:
          master: media_player.living_room_one
          entity_id: media_player.bedroom_one
      - service: media_player.volume_set
        data_template:
          entity_id:
            - media_player.living_room_one
            - media_player.bedroom_one
          volume_level: 0.5
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.living_room_one
          message: "{{ what }}"
      - delay:
          seconds: 1
      - delay: >-
          {% set duration = states.media_player.living_room_one.attributes.media_duration %}
          {% if duration > 0 %}
            {% set duration = duration - 1 %}
          {% endif %}
          {% set seconds = duration % 60 %}
          {% set minutes = (duration / 60)|int % 60 %}
          {% set hours = (duration / 3600)|int %}
          {{ [hours, minutes, seconds]|join(':') }}
      - service: media_player.sonos_restore
        data_template:
          entity_id:
            - media_player.living_room_one
            - media_player.bedroom_one
          with_group: yes
      - service: script.stream
        data_template:
          message: "{{'\U0001f4e2 Broadcast: '~ what}}"
  play_something_somewhere:
   sequence:
   - service: media_player.select_source
     data_template:
       entity_id: "{{ where }}"
       source: "{{ what }}"
  group_from_lr:
    sequence:
    - service: media_player.sonos_join
      data_template:
        master: media_player.living_room_one
        entity_id: media_player.bedroom_one
  group_from_br:
    sequence:
    - service: media_player.sonos_join
      data_template:
        master: media_player.bedroom_one
        entity_id: media_player.living_room_one
  unjoin_sonos:
    sequence:
    - service: media_player.sonos_unjoin
      data_template:
        entity_id:
          - media_player.living_room_one
          - media_player.bedroom_one
  sonos_reset:
    sequence:
    - service: media_player.media_stop
      data_template:
        entity_id:
          - media_player.living_room_one
          - media_player.bedroom_one
    - service: media_player.sonos_unjoin
      data_template:
        entity_id:
          - media_player.living_room_one
          - media_player.bedroom_one
    - service: media_player.volume_set
      data_template:
        entity_id:
          - media_player.living_room_one
          - media_player.bedroom_one
        volume_level: 0.25

  tts_test:
    sequence:
      - service: script.sonos_tts
        data_template:
          what: "{{ states('input_text.what') }}"
          where: "{{ states('input_select.where') }}"


group:
  audio_control:
    name: Audio
    entities:
      - input_text.dummy_player_lr_one
      - input_text.dummy_player_br_one
      - input_text.dummy_player_spotify
  sonos_lr:
    name: Living Room SONOS
    entities:
      - input_text.audio_tiles_lr
  sonos_br:
    name: Bedroom SONOS
    entities:
      - input_text.audio_tiles_br
  sonos_off:
    name: SONOS
    entities:
      - input_text.audio_tiles_off
  sonos_joined:
    name: SONOS Group
    entities:
      - input_text.audio_tiles_joined
  sonos_zone:
    name: SONOS Zones
    entities:
      - input_text.audio_tiles_multi

automation:

  - alias: LR Card Visible
    trigger:
      platform: template
      value_template: "{{ is_state('sensor.sonos_state', 'Living Room') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_lr
      data:
        visible: true

  - alias: LR Card Hidden
    trigger:
      platform: template
      value_template: "{{ not is_state('sensor.sonos_state', 'Living Room') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_lr
      data:
        visible: false

  - alias: BR Card Visible
    trigger:
      platform: template
      value_template: "{{ is_state('sensor.sonos_state', 'Bedroom') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_br
      data:
        visible: true

  - alias: BR Card Hidden
    trigger:
      platform: template
      value_template: "{{ not is_state('sensor.sonos_state', 'Bedroom') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_br
      data:
        visible: false

  - alias: Off Card Visible
    trigger:
      platform: template
      value_template: "{{ is_state('sensor.sonos_state', 'Off') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_off
      data:
        visible: true

  - alias: Off Card Hidden
    trigger:
      platform: template
      value_template: "{{ not is_state('sensor.sonos_state', 'Off') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_off
      data:
        visible: false

  - alias: Joined Card Visible
    trigger:
      platform: template
      value_template: "{{ is_state('sensor.sonos_state', 'Joined') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_joined
      data:
        visible: true

  - alias: Joined Card Hidden
    trigger:
      platform: template
      value_template: "{{ not is_state('sensor.sonos_state', 'Joined') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_joined
      data:
        visible: false

  - alias: Zoned Card Visible
    trigger:
      platform: template
      value_template: "{{ is_state('sensor.sonos_state', 'Multi Zone') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_zone
      data:
        visible: true

  - alias: Zoned Card Hidden
    trigger:
      platform: template
      value_template: "{{ not is_state('sensor.sonos_state', 'Multi Zone') }}"
    action:
      service: group.set_visibility
      entity_id: group.sonos_zone
      data:
        visible: false

  - alias: Set PP to LR
    trigger:
      - platform: state
        entity_id: input_boolean.pp_living_room_one
        from: 'off'
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.pp_bedroom_one
      - service: input_boolean.turn_off
        entity_id: input_boolean.pp_joined
      - service: input_select.select_option
        data:
          entity_id: input_select.primary_player
          option: "living_room_one"
  - alias: Set PP to BR
    trigger:
      - platform: state
        entity_id: input_boolean.pp_bedroom_one
        from: 'off'
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.pp_living_room_one
      - service: input_boolean.turn_off
        entity_id: input_boolean.pp_joined
      - service: input_select.select_option
        data:
          entity_id: input_select.primary_player
          option: "bedroom_one"
  - alias: Set PP to Joined
    trigger:
      - platform: state
        entity_id: input_boolean.pp_joined
        from: 'off'
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_one
      - service: input_boolean.turn_off
        entity_id: input_boolean.pp_bedroom_one
      - service: media_player.sonos_join
        data_template:
          master: media_player.living_room_one
          entity_id: media_player.bedroom_one
      - service: input_select.select_option
        data:
          entity_id: input_select.primary_player
          option: "living_room_one"

sensor:
  - platform: template
    sensors:
      sonos_state:
        friendly_name: "Sonos Grouping State"
        value_template: >-
          {% if (is_state("media_player.living_room_one", "playing") and is_state("media_player.bedroom_one", "playing")) and (state_attr('media_player.living_room_one', 'media_title') == state_attr('media_player.bedroom_one', 'media_title'))  -%}
            Joined
          {%- elif (is_state("media_player.living_room_one", "playing") and is_state("media_player.bedroom_one", "playing")) -%}
            Multi Zone
          {%- elif is_state("media_player.living_room_one", "playing") -%}
            Living Room
          {%- elif is_state("media_player.bedroom_one", "playing") -%}
            Bedroom
          {%- else -%}
            Off
          {%- endif %}



# Add the debug inputs for the developer settings
input_text:
  what:
    name: What to speak
    initial: "Hello, world"
  dummy_player_lr_one:
    name: Living Room One
  dummy_player_br_one:
    name: Bedroom One
  dummy_player_spotify:
    name: Spotify
  audio_tiles_lr:
    name: Living Room SONOS
  audio_tiles_br:
    name: Bedroom SONOS
  audio_tiles_off:
    name: SONOS
  audio_tiles_joined:
    name: SONOS Group
  audio_tiles_multi:
    name: SONOS Zones
input_select:
  where:
    name: Where to speak
    options:
     - bedroom_one
     - living_room_one
  primary_player:
    name: Primary Player
    options:
     - bedroom_one
     - living_room_one
input_boolean:
  pp_bedroom_one:
    name: SONOS Bedroom
  pp_living_room_one:
    name: SONOS Living Room
  pp_joined:
    name: SONOS Group
