# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:34
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 03/02/2018 15:30

# This package deals with what I hope will become whole home audio!
# Lots more work needed here! TODO: Almost everything!

homeassistant:
  customize:
    # media_player.snapcast_client_676c68d1dd024661b816a27cea8a6b4c:
    #   friendly_name: Vox One

media_player:

  # Squeezebox and snapcast removed, sonos in!

  - platform: spotify
    client_id: !secret spot_id
    client_secret: !secret spot_secret

  - platform: sonos
