# @Author: Will Scott <willscott>
# @Date:   14/10/2017 14:58
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 25/03/2018 18:36

# Conversations intents - e.g. for Alexa
# TODO: Pretty much everything.

intent_script:
  amzn1.ask.skill.76bad43c-950a-43c0-8727-3021eb795b24:
    speech:
      text: "Hello! I'm Ambassador. How can I help today?"

input_boolean:
  good_morning:
    icon: mdi:weather-sunny
  good_night:
    icon: mdi:weather-night
  stealth_mode:
    name: Stealth Mode
  goodbye:
    name: Goodbye

# Horrible duplication because of bugs (#239)
switch:
  - platform: template
    switches:
      good_morning:
        value_template: "{{ is_state('input_boolean.good_morning', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.good_morning
        turn_off:
          service: switch.turn_off
          data:
            entity_id: input_boolean.good_morning
      good_night:
        value_template: "{{ is_state('input_boolean.good_night', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.good_night
        turn_off:
          service: switch.turn_off
          data:
            entity_id: input_boolean.good_night
      stealth_mode:
        value_template: "{{ is_state('input_boolean.stealth_mode', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.stealth_mode
        turn_off:
          service: switch.turn_off
          data:
            entity_id: input_boolean.stealth_mode
      goodbye:
        value_template: "{{ is_state('input_boolean.goodbye', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.goodbye
        turn_off:
          service: switch.turn_off
          data:
            entity_id: input_boolean.goodbye
scene:
  - name: Good Night Lights
    entities:
      light.main:
        state: off
        transition: 5
      light.living_room:
        state: off
        transition: 30
      light.kitchen:
        state: off
        transition: 30
      light.hall:
        state: off
        transition: 45
      light.map_room:
        state: off
        transition: 45
      light.bedroom:
        state: off
        transition: 60
      light.ensuite:
        state: off
        transition: 30
      light.bathroom:
        state: off
        transition: 30
      light.utility:
        state: off
        transition: 30
  - name: Good Morning Lights
    entities:
      light.kitchen:
        state: on
      light.bedroom:
        state: on
  - name: Goodbye Lights
    entities:
      light.living_room:
        state: off
        transition: 30
      light.kitchen:
        state: off
      light.map_room:
        state: off
        transition: 45
      light.bedroom:
        state: off
        transition: 60
      light.ensuite:
        state: off
      light.bathroom:
        state: off
      light.utility:
        state: off

script:
  morning_tv:
    sequence:
      - service: remote.turn_on
        entity_id: "remote.living_room"
        data:
          activity: "Watch TV"
      - delay: 0:00:10
      - service: media_player.select_source
        entity_id: media_player.livingroomtv
        data:
          source: "LiveTV"
      - delay: 0:00:05
      - service: remote.send_command
        entity_id: remote.living_room
        data:
          device: "41500380"
          command: "1"
      - service: script.stream
        data:
          message: "\ud83d\udcfa BBC Breakfast is on"

automation:
# Morning and evening switch activation (awaiting Alexa fixes)
  - alias: 'Good Morning'
    trigger:
        platform: state
        entity_id: input_boolean.good_morning
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.good_morning_lights
      - service: script.morning_tv
      - service: media_player.sonos_set_sleep_timer
        entity_id:
          - media_player.bedroom_one
        data:
          sleep_time: 300
      - delay:
          minutes: 1
      - service: input_boolean.turn_off
        entity_id: input_boolean.good_morning

  - alias: 'Good Night'
    trigger:
        platform: state
        entity_id: input_boolean.good_night
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.good_night_lights
      - service: homeassistant.turn_off
        entity_id: switch.tv
      - service: script.sonos_tts
        data_template:
          what: >
           {%- if states("sensor.dan_workday_tomorrow") == "False" and states("sensor.will_workday_tomorrow") == "False" -%}
           There are no alarms set for tomorrow. Sleep well.
           {%- elif states("sensor.dan_workday_tomorrow") == "True" and states("sensor.will_workday_tomorrow") == "True" -%}
           Both alarms are set for tomorrow morning. Good night.
           {%- elif states("sensor.dan_workday_tomorrow") == "True" and states("sensor.will_workday_tomorrow") == "False" -%}
           Dan's alarm is set for tomorrow morning. Night night.
           {%- elif states("sensor.dan_workday_tomorrow") == "False" and states("sensor.will_workday_tomorrow") == "True" -%}
           Will's alarm is set for tomorrow morning. Nos da.
           {%- else -%}
           Good night.
           {%- endif %}
          where: "bedroom_one"
      - delay:
          minutes: 2
      - service: media_player.sonos_set_sleep_timer
        entity_id:
          - media_player.living_room_one
          - media_player.bedroom_one
        data:
          sleep_time: 1680
      - service: input_boolean.turn_off
        entity_id: input_boolean.good_night
      - service: script.stream
        data:
          message: "\ud83c\udf19 Good night!"

  - alias: 'Goodbye'
    trigger:
        platform: state
        entity_id: input_boolean.goodbye
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.goodbye_lights
      - service: homeassistant.turn_off
        entity_id: switch.tv
      - delay:
          minutes: 1
      - service: homeassistant.turn_off
        entity_id: light.hall
      - service: input_boolean.turn_off
        entity_id: input_boolean.goodbye

# Stealth mode - basically for when one person has an early alarm, wants to get up and out of bed but turn the alarm off!
  - alias: 'Stealth Mode Triggered'
    trigger:
      platform: state
      entity_id: input_boolean.stealth_mode
      to: 'on'
    action:
      # Turn off the lights in the bedroom
      - service: homeassistant.turn_off
        entity_id: light.bedroom
      # Turn on the kitchen lights
      - service: homeassistant.turn_on
        entity_id: light.kitchen
      # Turn off the radio
      - service: media_player.turn_off
        entity_id: media_player.bedroom_one
      # Reset the alarm
      - service: input_boolean.turn_off
        entity_id: input_boolean.alarm
      # Turn stealth mode back off
      - service: input_boolean.turn_off
        entity_id: input_boolean.stealth_mode
