# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:12
# @Project: Ambassadr Home Automation
# @Last modified by:   willscottuk
# @Last modified time: 25/06/2017 17:58

# This package deals with the internal climate.

tado:
  username: !secret tado_user
  password: !secret tado_pass

sensor:
  - platform: template
    sensors:
      heating_set_temp:
        value_template: '{{ states.sensor.heating_temperature.attributes.setting }}'
        friendly_name: 'Target Temperature'
        unit_of_measurement: 'ºC'


group:
  Internal:
    - sensor.heating_temperature
    - sensor.heating_humidity
    - sensor.heating_set_temp
    - sensor.heating_heating
    - sensor.heating_link
    - sensor.heating_tado_mode
