# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 19:03
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/01/2018 18:30

# This package sets up the lights in Ambassadr

homeassistant:
  customize_glob:
    "light.*":
      # By default I don't want individual lights exposed to Alexa via emulated hue. I think this is actually slightly redundant as I could just the light domain from the emulated hue settings.
      emulated_hue_hidden: false


light:
  - platform: lifx


# IKEA Trädfri now here (through autoconfig)

group:
  Lights:
    - group.living_room
    - group.hall
    - group.bedroom
    - group.map_room
    - group.bathroom
    - group.utility
    - group.kitchen
    - group.ensuite
  Living Room:
    - light.sofa
    - light.dining
  Hall:
    - light.hall_a
    - light.hall_b
  Bedroom:
    - light.main
    - light.daniel_side
    - light.will_side
  Map Room:
    - light.map
  Bathroom:
    - light.lf_bathroom
    - light.lr_bathroom
    - light.rf_bathroom
    - light.rr_bathroom
    - light.ro_bathroom
  Utility:
    - light.utility_light
  Kitchen:
    - light.rf_kitchen
    - light.lf_kitchen
    - light.rm_kitchen
    - light.lm_kitchen
    - light.rr_kitchen
    - light.lr_kitchen
  Ensuite:
    - light.r_ensuite
    - light.m_ensuite
    - light.l_ensuite
