# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 19:03
# @Project: Ambassadr Home Automation
# @Last modified by:   willscottuk
# @Last modified time: 24/06/2017 19:00

# This package sets up the lights in Ambassadr

homeassistant:
  customize:
    light.map_room:
      homebridge_name: Map Room Main


light:
  - platform: lifx

# IKEA Trädfri hopefully coming soon...


group:
  Lights:
    - group.living_room
    - group.hall
    - group.bedroom
    - group.map_room
  All Lights:
    - light.sofa
    - light.dining
    - light.bathroom
    - light.utility
    - light.map
    - light.main
    - light.will_side
    - light.daniel_side
  Living Room:
    - light.sofa
    - light.dining
  Hall:
    - light.bathroom
    - light.utility
  Bedroom:
    - light.main
    - light.daniel_side
    - light.will_side
  Map Room:
    - light.map

  ### Light Panels ##

  panel_bathroom:
    name: Bathroom
    control: hidden
    entities:
      - light.bathroom
      - sensor.bathroom_colour
      - sensor.bathroom_temp
      - sensor.bathroom_brightness

  panel_daniel:
    name: Daniel Side
    control: hidden
    entities:
      - light.daniel_side
      - sensor.daniel_colour
      - sensor.daniel_temp
      - sensor.daniel_brightness

  panel_dining:
    name: Dining
    control: hidden
    entities:
      - light.dining
      - sensor.dining_colour
      - sensor.dining_temp
      - sensor.dining_brightness

  panel_main:
    name: Main Bedroom
    control: hidden
    entities:
      - light.main
      - sensor.main_colour
      - sensor.main_temp
      - sensor.main_brightness

  panel_map:
    name: Map Room
    control: hidden
    entities:
      - light.map
      - sensor.map_colour
      - sensor.map_temp
      - sensor.map_brightness

  panel_sofa:
    name: Sofa
    control: hidden
    entities:
      - light.sofa
      - sensor.sofa_colour
      - sensor.sofa_temp
      - sensor.sofa_brightness

  panel_utility:
    name: Utility
    control: hidden
    entities:
      - light.utility
      - sensor.utility_colour
      - sensor.utility_temp
      - sensor.utility_brightness

  panel_will:
    name: Will Side
    control: hidden
    entities:
      - light.will_side
      - sensor.will_colour
      - sensor.will_temp
      - sensor.will_brightness

sensor:
  - platform: template
    sensors:
      bathroom_colour:
        value_template: '{{ states.light.bathroom.attributes.rgb_color }}'
        friendly_name: 'Bathroom Colour'

      bathroom_temp:
        value_template: '{{ 1000000.0 / states.light.bathroom.attributes.color_temp }}'
        friendly_name: 'Bathroom Colour Temp'
        unit_of_measurement: 'K'

      bathroom_brightness:
        value_template: '{{ states.light.bathroom.attributes.brightness }}'
        friendly_name: 'Bathroom Brightness'
        unit_of_measurement: 'n'

      daniel_colour:
        value_template: '{{ states.light.daniel_side.attributes.rgb_color }}'
        friendly_name: 'Daniel Side Colour'

      daniel_temp:
        value_template: '{{ 1000000.0 / states.light.daniel_side.attributes.color_temp }}'
        friendly_name: 'Daniel Side Colour Temp'
        unit_of_measurement: 'K'

      daniel_brightness:
        value_template: '{{ states.light.daniel_side.attributes.brightness }}'
        friendly_name: 'Daniel Side Brightness'
        unit_of_measurement: 'n'

      dining_colour:
        value_template: '{{ states.light.dining.attributes.rgb_color }}'
        friendly_name: 'Dining Colour'

      dining_temp:
        value_template: '{{ 1000000.0 / states.light.dining.attributes.color_temp }}'
        friendly_name: 'Dining Colour Temp'
        unit_of_measurement: 'K'

      dining_brightness:
        value_template: '{{ states.light.dining.attributes.brightness }}'
        friendly_name: 'Dining Brightness'
        unit_of_measurement: 'n'

      main_colour:
        value_template: '{{ states.light.main.attributes.rgb_color }}'
        friendly_name: 'Main Colour'

      main_temp:
        value_template: '{{ 1000000.0 / states.light.main.attributes.color_temp }}'
        friendly_name: 'Main Colour Temp'
        unit_of_measurement: 'K'

      main_brightness:
        value_template: '{{ states.light.main.attributes.brightness }}'
        friendly_name: 'Main Brightness'
        unit_of_measurement: 'n'

      map_colour:
        value_template: '{{ states.light.map.attributes.rgb_color }}'
        friendly_name: 'Map Colour'

      map_temp:
        value_template: '{{ 1000000.0 / states.light.map.attributes.color_temp }}'
        friendly_name: 'Map Colour Temp'
        unit_of_measurement: 'K'

      map_brightness:
        value_template: '{{ states.light.map.attributes.brightness }}'
        friendly_name: 'Map Brightness'
        unit_of_measurement: 'n'


      sofa_colour:
        value_template: '{{ states.light.sofa.attributes.rgb_color }}'
        friendly_name: 'Sofa Colour'

      sofa_temp:
        value_template: '{{ 1000000.0 / states.light.sofa.attributes.color_temp }}'
        friendly_name: 'Sofa Colour Temp'
        unit_of_measurement: 'K'

      sofa_brightness:
        value_template: '{{ states.light.sofa.attributes.brightness }}'
        friendly_name: 'Sofa Brightness'
        unit_of_measurement: 'n'

      utility_colour:
        value_template: '{{ states.light.utility.attributes.rgb_color }}'
        friendly_name: 'Utility Colour'

      utility_temp:
        value_template: '{{ 1000000.0 / states.light.utility.attributes.color_temp }}'
        friendly_name: 'Utility Colour Temp'
        unit_of_measurement: 'K'

      utility_brightness:
        value_template: '{{ states.light.utility.attributes.brightness }}'
        friendly_name: 'Utility Brightness'
        unit_of_measurement: 'n'

      will_colour:
        value_template: '{{ states.light.will_side.attributes.rgb_color }}'
        friendly_name: 'Will Side Colour'

      will_temp:
        value_template: '{{ 1000000.0 / states.light.will_side.attributes.color_temp }}'
        friendly_name: 'Will Side Colour Temp'
        unit_of_measurement: 'K'

      will_brightness:
        value_template: '{{ states.light.will_side.attributes.brightness }}'
        friendly_name: 'Will Side Brightness'
        unit_of_measurement: 'n'
