# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 19:03
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 10/03/2018 09:22

# This package sets up the lights in Ambassadr

homeassistant:
  customize_glob:
    "light.*":
      # By default I don't want individual lights exposed to Alexa via emulated hue. I think this is actually slightly redundant as I could just the light domain from the emulated hue settings.
      emulated_hue_hidden: false

circadian_lighting:
  interval: 300
  transition: 300

switch:
  - platform: circadian_lighting
    name: Bathroom
    lights_ct:
      - light.bathroom
      - light.ensuite
    max_brightness: 80
  - platform: circadian_lighting
    name: Hall
    lights_ct:
      - light.hall
    max_brightness: 60
  - platform: circadian_lighting
    name: Living
    lights_ct:
      - light.living_room
      - light.map_room
    disable_brightness_adjust: true
  - platform: circadian_lighting
    name: Bedroom
    lights_ct:
      - light.bedroom
    disable_brightness_adjust: true
    disable_entity: input_boolean.alarm
    disable_state: "on"

light:
  - platform: lifx
  # IKEA Trädfri now here (through autoconfig)
  - platform: group
    name: Kitchen
    entities:
      - light.rf_kitchen
      - light.lf_kitchen
      - light.rm_kitchen
      - light.lm_kitchen
      - light.rr_kitchen
      - light.lr_kitchen
  - platform: group
    name: Living Room
    entities:
      - light.sofa
      - light.dining
  - platform: group
    name: Hall
    entities:
      - light.hall_a
      - light.hall_b
  - platform: group
    name: Bedroom
    entities:
      - light.main
      - light.daniel_side
      - light.will_side
  - platform: group
    name: Map Room
    entities:
      - light.map
  - platform: group
    name: Bathroom
    entities:
      - light.lf_bathroom
      - light.lr_bathroom
      - light.rf_bathroom
      - light.rr_bathroom
      - light.ro_bathroom
  - platform: group
    name: Utility
    entities:
      - light.utility_light
  - platform: group
    name: Ensuite
    entities:
      - light.r_ensuite
      - light.m_ensuite
      - light.l_ensuite

group:
  Lights:
    - light.living_room
    - light.hall
    - light.bedroom
    - light.map_room
    - light.bathroom
    - light.utility
    - light.kitchen
    - light.ensuite

automation:
  - alias: 'Enable Circadian Lighting'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: homeassistant.turn_on
      data:
        entity_id:
          - switch.circadian_lighting_bathroom
          - switch.circadian_lighting_hall
          - switch.circadian_lighting_living
          - switch.circadian_lighting_bedroom
