# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 19:03
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 10/03/2018 09:22

# This package sets up the lights in Ambassadr

homeassistant:
  customize_glob:
    "light.*":
      # By default I don't want individual lights exposed to Alexa via emulated hue. I think this is actually slightly redundant as I could just the light domain from the emulated hue settings.
      emulated_hue_hidden: false
  customize:
    # Add some friendly names
    switch.circadian_lighting_bathroom:
      friendly_name: 'Circadian Downlights'
    switch.circadian_lighting_bedroom:
      friendly_name: 'Circadian Bedrooms'
    switch.circadian_lighting_hall:
      friendly_name: 'Circadian Hall'
    switch.circadian_lighting_living:
      friendly_name: 'Circadian Living Room'
    switch.circadian_lighting_utility:
      friendly_name: 'Circadian Utility'

circadian_lighting:
  interval: 30
  transition: 30
  sunset_offset: '0:45'

switch:
  - platform: circadian_lighting
    name: Bathroom
    lights_ct:
      - light.bathroom
      - light.ensuite
      - light.kitchen
    max_brightness: 80
    sleep_entity: input_boolean.sleep_mode
    sleep_state: 'on'
    sleep_colortemp: 2500
    sleep_brightness: 2
  - platform: circadian_lighting
    name: Utility
    lights_ct:
      - light.utility
    max_brightness: 80
    sleep_entity: input_boolean.sleep_mode
    sleep_state: 'on'
    sleep_colortemp: 2500
    sleep_brightness: 2
  - platform: circadian_lighting
    name: Hall
    lights_ct:
      - light.hall
    max_brightness: 60
    sleep_entity: input_boolean.sleep_mode
    sleep_state: 'on'
    sleep_colortemp: 2500
    sleep_brightness: 5
  - platform: circadian_lighting
    name: Living
    lights_ct:
      - light.sofa
      - light.dining
    disable_brightness_adjust: true
    sleep_entity: input_boolean.sleep_mode
    sleep_state: 'on'
    sleep_colortemp: 2500
  - platform: circadian_lighting
    name: Bedroom
    lights_ct:
      - light.main
      - light.daniel_side
      - light.will_side
      - light.map_room
    disable_brightness_adjust: true
    disable_entity: input_boolean.alarm
    disable_state: "on"

lifx:

light:
  # LIFX now has to be configured differently
  # - platform: lifx
  # IKEA Trädfri now here (through autoconfig)
  - platform: group
    name: Kitchen
    entities:
      - light.rf_kitchen
      - light.lf_kitchen
      - light.rm_kitchen
      - light.lm_kitchen
      - light.rr_kitchen
      - light.lr_kitchen
  - platform: group
    name: Living Room
    entities:
      - light.sofa
      - light.dining
  - platform: group
    name: Hall
    entities:
      - light.hall_a
      - light.hall_b
  - platform: group
    name: Bedroom
    entities:
      - light.main
      - light.daniel_side
      - light.will_side
  - platform: group
    name: Map Room
    entities:
      - light.map
  - platform: group
    name: Bathroom
    entities:
      - light.lf_bathroom
      - light.lr_bathroom
      - light.rf_bathroom
      - light.rr_bathroom
      - light.ro_bathroom
  - platform: group
    name: Utility
    entities:
      - light.utility_light
  - platform: group
    name: Ensuite
    entities:
      - light.r_ensuite
      - light.m_ensuite
      - light.l_ensuite
  - platform: switch
    name: Christmas Tree
    entity_id: switch.christmas_tree

group:
  Lights:
    - light.living_room
    - light.hall
    - light.bedroom
    - light.map_room
    - light.bathroom
    - light.utility
    - light.kitchen
    - light.ensuite
    - light.christmas_tree

automation:
  - alias: 'Enable Circadian Lighting'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: homeassistant.turn_on
      data:
        entity_id:
          - switch.circadian_lighting_bathroom
          - switch.circadian_lighting_hall
          - switch.circadian_lighting_living
          - switch.circadian_lighting_bedroom
          - switch.circadian_lighting_utility
