# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:30
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 03/02/2018 17:18


# This package deals with visual media

homeassistant:
  # Adds some friendly names for otherwise ugly named components.
  customize:
    media_player.plex_for_sony_playstation_4_0117:
      friendly_name: PS4
    media_player.snowdondefault:
      friendly_name: Bedroom Plex
    media_player.sfwk2tzxoz11c3difomifnfg:
      friendly_name: LR Plex
    media_player.lg_webos_tv_remote:
      friendly_name: LG TV
    # Ensure that the TV is exposed to Alexa. Potentially redundant.
    switch.tv:
      emulated_hue_hidden: false
    # Hide a few media players that don't need exposing!
    media_player.dan_iphone:
      hidden: true
    media_player.daniels_ipad:
      hidden: true
    media_player.will_iphone:
      hidden: true

media_player:
  - platform: plex
    # include_non_clients: true #This was causing errors in the log
    scan_interval: 5
    use_custom_entity_ids: true
    use_episode_art: true
  - platform: webostv
    host: 10.10.1.80
    name: LivingRoomTV
    customize:
      sources:
        - livetv
        - hdmi1
        - youtube
        - "Plex"
        - "All 4"
        - itv
        - netflix
        - bbc
  # The universal media player combines two players (here the Living Room Plex with the Living Room TV) to create one controllable entity. The ordering here means that Plex supersedes the TV if Plex is active.
  - platform: universal
    name: Living Room
    children:
      - media_player.sfwk2tzxoz11c3difomifnfg
      - media_player.livingroomtv
    commands:
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.living_room
          activity: "Watch TV"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.living_room
    attributes:
      state: remote.living_room
  # The PS4 is exposed here through a custom component: https://github.com/hmn/home-assistant-config/wiki/media_player_ps4
  # Seeing if I can stabalise this again.
  - platform: ps4
    host: !secret ps4ip

remote:
  - platform: harmony
    name: Living Room
    host: 10.10.1.81

switch:
  platform: template
  switches:
    tv:
      value_template: "{% if is_state('remote.living_room', 'on') %}on{% else %}off{% endif %}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.living_room
        data:
          entity_id: remote.living_room
          activity: "Watch TV"
      turn_off:
        service: script.tv_off

scene:
  - name: Media Off
    entities:
     remote.living_room:
        state: off

# Suave cinema mode (definitely one of the coolest scenes!)
  - name: Cinema
    entities:
     light.sofa:
        state: off
        transition: 10
     light.dining:
        state: on
        transition: 10
        brightness: 35

# I think that due to improvements to the speed of the Harmony component I might be able to get rid of this bit soon.
script:
  tv_off:
    sequence:
      - service: media_player.turn_off
        entity_id: media_player.livingroomtv
      - service: remote.turn_off
        entity_id: remote.living_room

automation:
  - alias: 'Auto Film Mode On'
    # Either thing changing will trigger film mode however both need to be true for it to turn on.
    trigger:
      - platform: template
        value_template: "{% if is_state_attr('media_player.sfwk2tzxoz11c3difomifnfg', 'media_content_type', 'movie') %}true{% endif %}"
      - platform: state
        entity_id: media_player.sfwk2tzxoz11c3difomifnfg
        to: 'playing'
    condition:
      - condition: template
        value_template: "{% if is_state_attr('media_player.sfwk2tzxoz11c3difomifnfg', 'media_content_type', 'movie') %}true{% endif %}"
      - condition: state
        entity_id: 'media_player.sfwk2tzxoz11c3difomifnfg'
        state: 'playing'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.film_mode

  - alias: 'Auto Film Mode Off'
    trigger:
      # There's a time requirement in here because sometimes buffering can cause issues!
      - platform: state
        entity_id: media_player.sfwk2tzxoz11c3difomifnfg
        to: 'paused'
        for:
          seconds: 30
      - platform: state
        entity_id: media_player.sfwk2tzxoz11c3difomifnfg
        to: 'idle'
        for:
          seconds: 30
    condition:
      - condition: state
        entity_id: input_boolean.film_mode
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.film_mode

  - alias: 'Cinema Lights'
    trigger:
      - platform: state
        entity_id: input_boolean.film_mode
        from: 'off'
        to: 'on'
    condition:
      # There's no point unless lights are already on!
      - condition: state
        entity_id: input_boolean.evening_mode
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.cinema

# This is one of those times when the Light Trigger is used (and useful)
  - alias: 'Reset Cinema Lights'
    trigger:
      - platform: state
        entity_id: input_boolean.film_mode
        from: 'on'
        to: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.light_trigger

# Visibility of media players

  - alias: Living Room TV Visible
    trigger:
      platform: template
      value_template: "{{ not is_state('media_player.living_room', 'off') }}"
    action:
      service: group.set_visibility
      entity_id: group.living_room_media
      data:
        visible: true

  - alias: Living Room TV Hidden
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: media_player.living_room
        to: 'off'
    action:
      service: group.set_visibility
      entity_id: group.living_room_media
      data:
        visible: false

  - alias: Spotify Card Visible
    trigger:
      platform: template
      value_template: "{{ not is_state('media_player.spotify', 'paused') }}"
    action:
      service: group.set_visibility
      entity_id: group.spotify_card
      data:
        visible: true

  - alias: Spotify Card Hidden
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: media_player.spotify
        to: 'paused'
        for:
          minutes: 5
      - platform: state
        entity_id: media_player.spotify
        to: 'idle'
        for:
          minutes: 3
      - platform: state
        entity_id: media_player.spotify
        to: 'off'
    action:
      service: group.set_visibility
      entity_id: group.spotify_card
      data:
        visible: false

  - alias: PS4 Visible
    trigger:
      platform: template
      value_template: "{{ not is_state('media_player.playstation_4', 'off') }}"
    action:
      service: group.set_visibility
      entity_id: group.playstation_4
      data:
        visible: true

  - alias: PS4 Hidden
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: media_player.playstation_4
        to: 'off'
    action:
      service: group.set_visibility
      entity_id: group.playstation_4
      data:
        visible: false

group:
  # Analagous audio groups exist in the audio package
  playstation_4:
    entities:
      - media_player.playstation_4
  living_room_media:
    entities:
      - media_player.living_room
