# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:21
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 23/01/2018 21:47

# This is a package for (mostly) manual though their effects are felt in just about every other package.

input_boolean:

  holiday_mode:
    initial: off
    name: Holiday
    icon: mdi:beach

  guest_mode:
    initial: off
    name: Guest
    icon: mdi:account-multiple

  party_mode:
    initial: off
    name: Party
    icon: mdi:cake-variant

  romance_mode:
    initial: off
    name: Romance
    icon: mdi:heart

  quiet_mode:
    initial: off
    name: Quiet
    icon: mdi:volume-off

  film_mode:
    initial: off
    name: Film
    icon: mdi:movie

group:
  manual_modes:
    name: Manual Modes
    control: hidden
    entities:
      - input_boolean.holiday_mode
      - input_boolean.guest_mode
      - input_boolean.romance_mode
      - input_boolean.party_mode
      - input_boolean.quiet_mode
      - input_boolean.film_mode

##################################
#
#          GUEST MODE
#
##################################

# If guest_mode is on, there should be an alert sent out to our devices.

alert:
  guest_mode:
    name: Guest Mode is on
    done_message: Guest mode is off
    entity_id: input_boolean.guest_mode
    state: 'on'
    repeat:
      - 30
      - 90
      - 360
    can_acknowledge: false
    skip_first: false
    notifiers:
      - notify.will
      - notify.dan

automation:
  - alias: 'Guests Home'
    trigger:
      platform: state
      entity_id: sensor.front_door_access_control
      to: '22'
    condition:
      # Guest mode needs to be on
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'on'
      # Both Will and Dan need to be away
      - condition: state
        entity_id: device_tracker.will_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.dan_iphone
        state: 'not_home'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.away_mode
      - service: script.notify_all
        data:
          title: "\U000026A0 Flat Occupied"
          message: "The door just opened while in guest mode!"
