# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:02
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 30/06/2018 18:30

# This package deals with internal monitoring - both inside the flat and inside the server

homeassistant:
  customize:
    # Add some friendly names
    sensor.power_usage:
      friendly_name: 'Electricity'
      icon: mdi:speedometer
    sensor.speedtest_ping:
      icon: mdi:pulse
    sensor.speedtest_download:
      icon: mdi:cloud-download
    sensor.speedtest_upload:
      icon: mdi:cloud-upload
    sensor.disk_use_percent_mediabumblebee:
      friendly_name: "Bumblebee"
    sensor.disk_use_percent_mediadragonfly:
      friendly_name: "Dragonfly"
    sensor.since_last_boot:
      friendly_name: "Uptime"
    sensor.electricity_usage:
      icon: mdi:flash-circle
    sensor.tumble_dryer_current:
      icon: mdi:washing-machine
    sensor.air_quality:
      icon: mdi:home-heart
    sensor.memory_use_percent:
      friendly_name: Memory use
    sensor.basecamp_living_room_air_quality:
      friendly_name: Air Quality
      unit_of_measurement: AQU

switch:
  - platform: tplink
    host: !secret dryer_ip
    name: "Tumble Dryer"

# Docker switches
  - platform: rest
    resource: !secret portainer
    name: Portainer
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: !secret influxdb
    name: InfluxDB
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: !secret tautuli
    name: Tautuli
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: !secret openvpn
    name: OpenVPN
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  - platform: rest
    resource: !secret plex
    name: OpenVPN
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: error

sensor:
  - platform: version
    name: Installed HA version
  - platform: loopenergy
    electricity:
      electricity_serial: !secret loop_serial
      electricity_secret: !secret loop_secret
  - platform: fastdotcom
    minute:
      - 15
  - platform: statistics
    entity_id: sensor.power_usage
    name: Power Stats
    max_age:
      minutes: 10
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: !secret disk
      - type: disk_use_percent
        arg: !secret disk2
      - type: memory_use_percent
      - type: processor_use
  - platform: cpuspeed
  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA upstream
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600
  - platform: template
    sensors:
      electricity_usage:
        friendly_name: "Electricity Usage"
        value_template: >-
          {%- if states("sensor.power_stats_mean") | float < 0.3 -%}
            Low
          {%- elif states("sensor.power_stats_mean") | float < 1.0 -%}
            Moderate
          {%- elif states("sensor.power_stats_mean") | float >= 1.0 -%}
            High
          {%- else -%}
            Unknown
          {%- endif -%}
      tumble_dryer_current:
        friendly_name: 'Tumble Dryer Current'
        # The attribute changed in 0.61
        value_template: '{{ states.switch.tumble_dryer.attributes["current_power_w"].split(" ")[0] }}'
        unit_of_measurement: 'W'
      air_quality:
        friendly_name: "Air Quality"
        value_template: >-
          {%- if states("sensor.basecamp_living_room_air_quality") | float <= 0.4 -%}
            Very Abnormal
          {%- elif states("sensor.basecamp_living_room_air_quality") | float <= 0.6 -%}
            Abnomrmal
          {%- elif states("sensor.basecamp_living_room_air_quality") | float <= 1.0 -%}
            Normal
          {%- else -%}
            Unknown
          {%- endif -%}
      shower_on:
        friendly_name: "Shower Status"
        value_template: "{{ states('sensor.humidity_158d00022cb6b0')|float > (states('sensor.average_humidity')|float + 7) }}"
      bath_on:
        friendly_name: "Bath Status"
        value_template: "{{ states('sensor.humidity_158d00022b584d')|float > (states('sensor.average_humidity')|float + 7) }}"
  # This monitors the continuous integration status of Ambassadr.
  # Automations using this are down below: Configuration Update.
  - platform: travisci
    api_key: !secret travisci

  - platform: pi_hole
    host: !secret pihole
  - platform: cert_expiry
    host: !secret base_url

speedtestdotnet:
  monitored_conditions:
    - download
    - upload
  server_id: 4078

linode:
  access_token: !secret linode

group:
  System:
    - sensor.disk_use_percent_mediadragonfly
    - sensor.disk_use_percent_mediabumblebee
    - sensor.memory_use_percent
    - sensor.processor_use
    - sensor.cpu_speed
  Speed:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.fastcom_download
  Power:
    -  sensor.power_usage
    -  sensor.power_stats_mean
    -  sensor.electricity_usage
    -  sensor.tumble_dryer_current
  Developer:
    control: hidden
    entities:
      - input_select.log_level
      - input_text.what
      - input_select.where
      - script.tts_test
      - input_boolean.light_trigger
  Docker:
    control: hidden
    entities:
      - switch.portainer
      - switch.influxdb
      - switch.tautuli
      - switch.openvpn
      - switch.plex

automation:
  - alias: "Configuration Update"
    trigger:
      platform: state
      entity_id: sensor.ambassadrhomeassistant_last_build_finished_at
    condition:
      - condition: state
        entity_id: sensor.ambassadrhomeassistant_last_build_state
        state: 'passed'
      - condition: template
        value_template: '{{states.sensor.ambassadrhomeassistant_last_build_finished_at.attributes["Commit Branch"] == "master"}}'
      - condition: template
        value_template: '{{states.sensor.ambassadrhomeassistant_last_build_finished_at != "unknown"}}'
    action:
      - service: script.configuation_update

  - alias: Log Level
    trigger:
      platform: state
      entity_id: input_select.log_level
    action:
      service: logger.set_level
      data_template:
        homeassistant.components: "{{ trigger.to_state.state }}"

  - alias: 'Start HomeKit'
    trigger:
      - platform: event
        event_type: zwave.network_ready
    action:
      - service: homekit.start

  - alias: 'Stream on Start'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.stream
      data:
        message: "\u267b Home Assistant restarted"

script:
  configuation_update:
    sequence:
      - service: shell_command.git_pull
      - service: notify.will
        data_template:
          title: "\U000026A1 Restarting HomeAssistant Now"
          message: "Restarting in 30 seconds to update to new build"
      - service: script.stream
        data:
          message: "\U000026A1 Config update installing..."
      - delay: 00:00:30
      - service: homeassistant.restart

shell_command:
  git_pull: 'bash /home/homeassistant/.homeassistant/scripts/git_pull.sh'
