# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:46
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 16/07/2017 18:15

# This package deals with notifications - both text and speech
# I've also added an "update available" notification in here.

notify:
  - platform: slack
    name: slack
    api_key: !secret slack
    default_channel: '#stream'
  - platform: webostv
    host: 10.10.1.80
    name: livingroom_tv
  - platform: ios
  - platform: facebook
    page_access_token: !secret fb
    name: fb
  - name: everyone
    platform: group
    services:
      - service: ios_dan_iphone
      - service: ios_will_iphone
      - service: slack

tts:
  - platform: google
    language: 'en-uk'

automation:
  alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_will_iphone
    data:
      title: "\U0001f4f0 Update Available"
      message: 'A new update for Home Assistant is available.'
