# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:46
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 25/03/2018 18:22

# This package deals with text-based Notifications
# For audio notifications (inc text to speech) see the audio package
# I've also added an "update available" notification in here.

notify:
  - platform: slack
    name: slack
    api_key: !secret slack
    default_channel: '#stream'
  - platform: webostv
    host: 10.10.1.80
    name: livingroom_tv
  - platform: ios
  - platform: facebook
    page_access_token: !secret fb
    name: fb
  - name: everyone
    platform: group
    services:
      - service: ios_dan_iphone
      - service: ios_will_iphone
  - name: will
    platform: group
    services:
      - service: ios_will_iphone
  - name: dan
    platform: group
    services:
      - service: ios_dan_iphone
  - name: nobody
    platform: group
    services:
      - service: slack

automation:
  alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_will_iphone
    data:
      title: "\U0001f4f0 Update Available"
      message: 'A new update for Home Assistant is available.'


script:

  # This only notifies whoever is at home
  notify_home:
    sequence:
      - service_template: >
          {%- if is_state("input_boolean.will_home", "on") and is_state("input_boolean.dan_home", "on") -%}
            notify.everyone
          {%- elif is_state("input_boolean.will_home", "on") and is_state("input_boolean.dan_home", "off") -%}
            notify.will
          {%- elif is_state("input_boolean.will_home", "off") and is_state("input_boolean.dan_home", "on") -%}
            notify.dan
          {%- else -%}
            notify.nobody
          {%- endif -%}
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"

  # This only notifies whoever is away
  notify_away:
    sequence:
      - service_template: >
          {%- if is_state("input_boolean.will_home", "off") and is_state("input_boolean.dan_home", "off") -%}
            notify.everyone
          {%- elif is_state("input_boolean.will_home", "on") and is_state("input_boolean.dan_home", "off") -%}
            notify.dan
          {%- elif is_state("input_boolean.will_home", "off") and is_state("input_boolean.dan_home", "on") -%}
            notify.will
          {%- else -%}
            notify.nobody
          {%- endif -%}
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"

  # This notifies everyone (on all systems)
  notify_all:
    sequence:
      - service: notify.will
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
      - service: notify.dan
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
      - service: persistent_notification.create
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
          notification_id: "404"

  stream:
    sequence:
      - service: notify.slack
        data_template:
          message: "{{ message }}"

# iOS notification config has to be in the main config file :(
