# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:46
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 08/08/2017 18:25

# This package deals with notifications - both text and speech
# I've also added an "update available" notification in here.

notify:
  - platform: slack
    name: slack
    api_key: !secret slack
    default_channel: '#stream'
  - platform: webostv
    host: 10.10.1.80
    name: livingroom_tv
  - platform: ios
  - platform: facebook
    page_access_token: !secret fb
    name: fb
  - name: everyone
    platform: group
    services:
      - service: ios_dan_iphone
      - service: ios_will_iphone
  - name: will
    platform: group
    services:
      - service: ios_will_iphone
  - name: dan
    platform: group
    services:
      - service: ios_dan_iphone
  - name: nobody
    platform: group
    services:
      - service: slack

tts:
  - platform: google
    language: 'en-uk'

automation:
  alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_will_iphone
    data:
      title: "\U0001f4f0 Update Available"
      message: 'A new update for Home Assistant is available.'

script:
  notify_home:
    sequence:
      - service: notify.slack
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"

      - service: notify.livingroom_tv
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"

      - service_template: >
          {%- if is_state("input_boolean.will_home", "on") and is_state("input_boolean.dan_home", "on") -%}
            notify.everyone
          {%- elif is_state("input_boolean.will_home", "on") and is_state("input_boolean.dan_home", "off") -%}
            notify.will
          {%- elif is_state("input_boolean.will_home", "off") and is_state("input_boolean.dan_home", "on") -%}
            notify.dan
          {%- else -%}
            notify.nobody
          {%- endif -%}
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"
script:
  notify_away:
    sequence:
      - service: notify.slack
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"

        - service_template: >
            {%- if is_state("input_boolean.will_home", "off") and is_state("input_boolean.dan_home", "off") -%}
              notify.everyone
            {%- elif is_state("input_boolean.will_home", "on") and is_state("input_boolean.dan_home", "off") -%}
              notify.dan
            {%- elif is_state("input_boolean.will_home", "off") and is_state("input_boolean.dan_home", "on") -%}
              notify.will
            {%- else -%}
              notify.nobody
            {%- endif -%}
          data_template:
            title: "{{ notify_title }}"
            message: "{{ notify_text }}"
script:
  notify_all:
    sequence:
      - service: notify.will
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"
      - service: notify.dan
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"
      - service: notify.slack
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"
      - service_template: >
          {%- if is_state("input_boolean.will_home", "on") or is_state("input_boolean.dan_home", "on") -%}
            notify.livingroom_tv
          {%- else -%}
            persistent_notification.create
          {%- endif -%}
        data_template:
          title: "{{ notify_title }}"
          message: "{{ notify_text }}"

ios:
  push:
    categories:
      - name: Morning
        identifier: 'MORNING'
        actions:
          - identifier: 'TV_ON'
            title: 'Switch on BBC One'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'COFFEE_ON'
            title: 'Brew Coffee'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
