# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:07
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 04/09/2017 20:42

# Because plants are cool. And green.

homeassistant:
  customize:
     sensor.aquatica_temperature:
       icon: mdi:oil-temperature
     sensor.aquatica_moisture:
       icon: mdi:water-percent
     sensor.aquatica_brightness:
       icon: mdi:brightness-7
     sensor.aquatica_conductivity:
       icon: mdi:flash
     sensor.aquatica_battery:
       icon: mdi:battery-charging

     sensor.aloe_temperature:
       icon: mdi:oil-temperature
     sensor.aloe_moisture:
       icon: mdi:water-percent
     sensor.aloe_brightness:
       icon: mdi:brightness-7
     sensor.aloe_conductivity:
       icon: mdi:flash
     sensor.aloe_battery:
       icon: mdi:battery-charging

     sensor.chilli_temperature:
       icon: mdi:oil-temperature
     sensor.chilli_moisture:
       icon: mdi:water-percent
     sensor.chilli_brightness:
       icon: mdi:brightness-7
     sensor.chilli_conductivity:
       icon: mdi:flash
     sensor.chilli_battery:
       icon: mdi:battery-charging

     sensor.basic_temperature:
       icon: mdi:oil-temperature
     sensor.basil_moisture:
       icon: mdi:water-percent
     sensor.basil_brightness:
       icon: mdi:brightness-7
     sensor.basil_conductivity:
       icon: mdi:flash
     sensor.basil_battery:
       icon: mdi:battery-charging

     sensor.will_tree_temperature:
       icon: mdi:oil-temperature
     sensor.will_tree_moisture:
       icon: mdi:water-percent
     sensor.will_tree_brightness:
       icon: mdi:brightness-7
     sensor.will_tree_conductivity:
       icon: mdi:flash
     sensor.will_tree_battery:
       icon: mdi:battery-charging

     sensor.dan_tree_temperature:
       icon: mdi:oil-temperature
     sensor.dan_tree_moisture:
       icon: mdi:water-percent
     sensor.dan_tree_brightness:
       icon: mdi:brightness-7
     sensor.dan_tree_conductivity:
       icon: mdi:flash
     sensor.dan_tree_battery:
       icon: mdi:battery-charging

     group.all_plants:
       friendly_name: Plant Status
       hidden: false

sensor:
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

group:
  aquatica:
    name: Aquatica
    control: hidden
    entities:
      - sensor.aquatica_temperature
      - sensor.aquatica_moisture
      - sensor.aquatica_brightness
      - sensor.aquatica_conductivity
      - sensor.aquatica_battery

  aloe:
    name: Aloe
    control: hidden
    entities:
      - sensor.aloe_temperature
      - sensor.aloe_moisture
      - sensor.aloe_brightness
      - sensor.aloe_conductivity
      - sensor.aloe_battery

  chilli:
    name: Chilli
    control: hidden
    entities:
      - sensor.chilli_temperature
      - sensor.chilli_moisture
      - sensor.chilli_brightness
      - sensor.chilli_conductivity
      - sensor.chilli_battery

  basil:
    name: Basil
    control: hidden
    entities:
      - sensor.basil_temperature
      - sensor.basil_moisture
      - sensor.basil_brightness
      - sensor.basil_conductivity
      - sensor.basil_battery

  will_tree:
    name: Will's Tree
    control: hidden
    entities:
      - sensor.will_tree_temperature
      - sensor.will_tree_moisture
      - sensor.will_tree_brightness
      - sensor.will_tree_conductivity
      - sensor.will_tree_battery

  plant_status:
    name: Plant Status
    control: hidden
    entities:
      - sensor.water_plants

  dan_tree:
    name: Dan's Tree
    control: hidden
    entities:
      - sensor.dan_tree_temperature
      - sensor.dan_tree_moisture
      - sensor.dan_tree_brightness
      - sensor.dan_tree_conductivity
      - sensor.dan_tree_battery

# Smart Plants

plant:
  aquatica:
    sensors:
      moisture: sensor.aquatica_moisture
      battery: sensor.aquatica_battery
      temperature: sensor.aquatica_temperature
      conductivity: sensor.aquatica_conductivity
      brightness: sensor.aquatica_brightness
    min_moisture: 10
  aloe:
    sensors:
      moisture: sensor.aloe_moisture
      battery: sensor.aloe_battery
      temperature: sensor.aloe_temperature
      conductivity: sensor.aloe_conductivity
      brightness: sensor.aloe_brightness
    min_moisture: 10
  chilli:
    sensors:
      moisture: sensor.chilli_moisture
      battery: sensor.chilli_battery
      temperature: sensor.chilli_temperature
      conductivity: sensor.chilli_conductivity
      brightness: sensor.chilli_brightness
    min_moisture: 20
  basil:
    sensors:
      moisture: sensor.basil_moisture
      battery: sensor.basil_battery
      temperature: sensor.basil_temperature
      conductivity: sensor.basil_conductivity
      brightness: sensor.basil_brightness
    min_moisture: 20
  will_tree:
    sensors:
      moisture: sensor.will_tree_moisture
      battery: sensor.will_tree_battery
      temperature: sensor.will_tree_temperature
      conductivity: sensor.will_tree_conductivity
      brightness: sensor.will_tree_brightness
    min_moisture: 10
  dan_tree:
    sensors:
      moisture: sensor.dan_tree_moisture
      battery: sensor.dan_tree_battery
      temperature: sensor.dan_tree_temperature
      conductivity: sensor.dan_tree_conductivity
      brightness: sensor.dan_tree_brightness
    min_moisture: 10

# Update Plant Status

automation:
    - alias: 'Plant Update'
      trigger:
        - platform: state
          entity_id: plant.aquatica, plant.aloe, plant.chilli, plant.basil, plant.will_tree, plant.dan_tree
      action:
        - service: python_script.plant_problems
