# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:07
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 11/02/2018 17:35

# Because plants are cool. And green.

homeassistant:
  customize:
    plant.aquatica:
      friendly_name: Aquatica
    plant.aloe:
      friendly_name: Aloe
    plant.chilli:
      friendly_name: Chilli
    plant.basil:
      friendly_name: Basil
    plant.dan_tree:
      friendly_name: Dan's Tree
    plant.will_tree:
      friendly_name: Will's Tree

group:

  plants:
    name: Plants
    control: hidden
    entities:
      - plant.aquatica
      - plant.aloe
      - plant.chilli
      - plant.basil
      - plant.dan_tree
      - plant.will_tree

  plant_switches:
    name: Plant Monitoring
    control: hidden
    entities:
      - input_boolean.plant_aquatica
      - input_boolean.plant_aloe
      - input_boolean.plant_chilli
      - input_boolean.plant_basil
      - input_boolean.plant_dan_tree
      - input_boolean.plant_will_tree

  plant_status:
    name: Plant Status
    control: hidden
    entities:
      - sensor.water_plants

sensor:
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aquatica/'
      name: 'Aquatica Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/aloe/'
      name: 'Aloe Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/chilli/'
      name: 'Chilli Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/basil/'
      name: 'Basil Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/willtree/'
      name: 'Will Tree Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'

    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Moisture'
      unit_of_measurement: '%'
      value_template: '{{ value_json.moisture }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Conductivity'
      unit_of_measurement: 'µS/cm'
      value_template: '{{ value_json.conductivity }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Brightness'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.brightness }}'
    - platform: mqtt
      state_topic: 'flora/my/plants/dantree/'
      name: 'Dan Tree Battery'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'


# Smart Plants

plant:
  aquatica:
    sensors:
      moisture: sensor.aquatica_moisture
      battery: sensor.aquatica_battery
      temperature: sensor.aquatica_temperature
      conductivity: sensor.aquatica_conductivity
      brightness: sensor.aquatica_brightness
    min_moisture: 10
  aloe:
    sensors:
      moisture: sensor.aloe_moisture
      battery: sensor.aloe_battery
      temperature: sensor.aloe_temperature
      conductivity: sensor.aloe_conductivity
      brightness: sensor.aloe_brightness
    min_moisture: 10
  chilli:
    sensors:
      moisture: sensor.chilli_moisture
      battery: sensor.chilli_battery
      temperature: sensor.chilli_temperature
      conductivity: sensor.chilli_conductivity
      brightness: sensor.chilli_brightness
    min_moisture: 20
  basil:
    sensors:
      moisture: sensor.basil_moisture
      battery: sensor.basil_battery
      temperature: sensor.basil_temperature
      conductivity: sensor.basil_conductivity
      brightness: sensor.basil_brightness
    min_moisture: 20
  will_tree:
    sensors:
      moisture: sensor.will_tree_moisture
      battery: sensor.will_tree_battery
      temperature: sensor.will_tree_temperature
      conductivity: sensor.will_tree_conductivity
      brightness: sensor.will_tree_brightness
    min_moisture: 10
  dan_tree:
    sensors:
      moisture: sensor.dan_tree_moisture
      battery: sensor.dan_tree_battery
      temperature: sensor.dan_tree_temperature
      conductivity: sensor.dan_tree_conductivity
      brightness: sensor.dan_tree_brightness
    min_moisture: 10

# An input_boolean for each plant - this allows plans to be switched off from status updates during winter (/ if we accidentally kill one)

input_boolean:
  plant_aquatica:
    name: Aquatica Monitoring
    icon: mdi:leaf
  plant_aloe:
    name: Aloe Monitoring
    icon: mdi:leaf
  plant_chilli:
    name: Chilli Monitoring
    icon: mdi:leaf
  plant_basil:
    name: Basil Monitoring
    icon: mdi:leaf
  plant_will_tree:
    name: Will's Tree Monitoring
    icon: mdi:leaf
  plant_dan_tree:
    name: Dan's Tree Monitoring
    icon: mdi:leaf

# Update Plant Status

automation:
    - alias: 'Plant Update'
      trigger:
        - platform: state
          entity_id: plant.aquatica, plant.aloe, plant.chilli, plant.basil, plant.will_tree, plant.dan_tree
      action:
        - service: python_script.plant_status
