# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:07
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 21/01/2018 20:33

# Because plants are cool. And green.

homeassistant:
  customize:
    plant.aquatica:
      friendly_name: Aquatica Status
    plant.aloe:
      friendly_name: Aloe Status
    plant.chilli:
      friendly_name: Chilli Status
    plant.basil:
      friendly_name: Basil Status
    plant.dan_tree:
      friendly_name: Dan's Tree Status
    plant.will_tree:
      friendly_name: Will's Tree Status

    group.all_plants:
      friendly_name: Plant Status
      hidden: false

group:

  plants:
    name: Plants
    control: hidden
    entities:
      - input_boolean.plant_aquatica
      - plant.aquatica
      - input_boolean.plant_aloe
      - plant.aloe
      - input_boolean.plant_chilli
      - plant.chilli
      - input_boolean.plant_basil
      - plant.basil
      - input_boolean.plant_dan_tree
      - plant.dan_tree
      - input_boolean.plant_will_tree
      - plant.will_tree

  plant_status:
    name: Plant Status
    control: hidden
    entities:
      - sensor.water_plants

# DEPRECATED
  aquatica:
    name: Aquatica
    control: hidden
    entities:
      - input_boolean.plant_aquatica
      - sensor.aquatica_temperature
      - sensor.aquatica_moisture
      - sensor.aquatica_brightness
      - sensor.aquatica_conductivity
      - sensor.aquatica_battery

  aloe:
    name: Aloe
    control: hidden
    entities:
      - input_boolean.plant_aloe
      - sensor.aloe_temperature
      - sensor.aloe_moisture
      - sensor.aloe_brightness
      - sensor.aloe_conductivity
      - sensor.aloe_battery

  chilli:
    name: Chilli
    control: hidden
    entities:
      - input_boolean.plant_chilli
      - sensor.chilli_temperature
      - sensor.chilli_moisture
      - sensor.chilli_brightness
      - sensor.chilli_conductivity
      - sensor.chilli_battery

  basil:
    name: Basil
    control: hidden
    entities:
      - input_boolean.plant_basil
      - sensor.basil_temperature
      - sensor.basil_moisture
      - sensor.basil_brightness
      - sensor.basil_conductivity
      - sensor.basil_battery

  will_tree:
    name: Will's Tree
    control: hidden
    entities:
      - input_boolean.plant_will_tree
      - sensor.will_tree_temperature
      - sensor.will_tree_moisture
      - sensor.will_tree_brightness
      - sensor.will_tree_conductivity
      - sensor.will_tree_battery

  dan_tree:
    name: Dan's Tree
    control: hidden
    entities:
      - input_boolean.plant_dan_tree
      - sensor.dan_tree_temperature
      - sensor.dan_tree_moisture
      - sensor.dan_tree_brightness
      - sensor.dan_tree_conductivity
      - sensor.dan_tree_battery


# Smart Plants

plant:
  aquatica:
    sensors:
      moisture: sensor.aquatica_moisture
      battery: sensor.aquatica_battery
      temperature: sensor.aquatica_temperature
      conductivity: sensor.aquatica_conductivity
      brightness: sensor.aquatica_brightness
    min_moisture: 10
  aloe:
    sensors:
      moisture: sensor.aloe_moisture
      battery: sensor.aloe_battery
      temperature: sensor.aloe_temperature
      conductivity: sensor.aloe_conductivity
      brightness: sensor.aloe_brightness
    min_moisture: 10
  chilli:
    sensors:
      moisture: sensor.chilli_moisture
      battery: sensor.chilli_battery
      temperature: sensor.chilli_temperature
      conductivity: sensor.chilli_conductivity
      brightness: sensor.chilli_brightness
    min_moisture: 20
  basil:
    sensors:
      moisture: sensor.basil_moisture
      battery: sensor.basil_battery
      temperature: sensor.basil_temperature
      conductivity: sensor.basil_conductivity
      brightness: sensor.basil_brightness
    min_moisture: 20
  will_tree:
    sensors:
      moisture: sensor.will_tree_moisture
      battery: sensor.will_tree_battery
      temperature: sensor.will_tree_temperature
      conductivity: sensor.will_tree_conductivity
      brightness: sensor.will_tree_brightness
    min_moisture: 10
  dan_tree:
    sensors:
      moisture: sensor.dan_tree_moisture
      battery: sensor.dan_tree_battery
      temperature: sensor.dan_tree_temperature
      conductivity: sensor.dan_tree_conductivity
      brightness: sensor.dan_tree_brightness
    min_moisture: 10

# An input_boolean for each plant - this allows plans to be switched off from status updates during winter (/ if we accidentally kill one)

input_boolean:
  plant_aquatica:
    name: Aquatica Monitoring
    icon: mdi:leaf
  plant_aloe:
    name: Aloe Monitoring
    icon: mdi:leaf
  plant_chilli:
    name: Chilli Monitoring
    icon: mdi:leaf
  plant_basil:
    name: Basil Monitoring
    icon: mdi:leaf
  plant_will_tree:
    name: Will's Tree Monitoring
    icon: mdi:leaf
  plant_dan_tree:
    name: Dan's Tree Monitoring
    icon: mdi:leaf

# Update Plant Status

automation:
    - alias: 'Plant Update'
      trigger:
        - platform: state
          entity_id: plant.aquatica, plant.aloe, plant.chilli, plant.basil, plant.will_tree, plant.dan_tree
      action:
        - service: python_script.plant_status
