# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:40
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 09/12/2017 17:05

# This package deals with making it a Secure and Stable flat ;) #Election2017

# This connects Canary to HASS. It's not pretty but it works! Shame there's no camera access.

homeassistant:
  customize:
    binary_sensor.front_door_sensor:
      friendly_name: "Front Door"
      icon: mdi:exit-to-app

camera:
  - platform: mjpeg
    mjpeg_url: http://10.10.1.30:2971/camera/stream

sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {% if is_state('sensor.front_door_access_control', '23') %}
            closed
          {% else %}
            open
          {% endif %}

input_boolean:

  front_door:
    initial: off
    name: Front Door
    icon: mdi:exit-to-app

automation:

  - alias: 'Lockdown'
    trigger:
         platform: state
         entity_id: group.people
         from: 'on'
         to: 'off'
    action:
        - service: light.turn_off
          entity_id: group.all_lights
        - service: alarm_control_panel.alarm_arm_away
          entity_id: alarm_control_panel.living_room
        - service: script.notify_all
          data:
            title: "\U0001F512 Lockdown"
            message: "Everyone's Away - Everything is off and Canary is armed and ready!"
        - service: input_boolean.turn_off
          entity_id: input_boolean.home_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.away_mode

  - alias: 'Front Door Opened'
    trigger:
        platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door
      - service: input_boolean.turn_on
        entity_id: input_boolean.front_door
      - service: notify.will
        data:
          title: "\U0001F6AA Door Open"
          message: "#SecureByDefault"

  - alias: 'Front Door Expiry'
    trigger:
        platform: state
        entity_id: input_boolean.front_door
        to: 'on'
        for:
          minutes: 5
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door

  - alias: 'Occupied'
    trigger:
         platform: state
         entity_id: group.people
         from: 'off'
         to: 'on'
    action:
        - service: input_boolean.turn_off
          entity_id: input_boolean.away_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.home_mode
        - service: alarm_control_panel.alarm_disarm
          entity_id: alarm_control_panel.living_room
        - service: persistent_notification.dismiss
          data:
            notification_id: "404"

  - alias: 'Auto holiday mode'
    trigger:
        platform: time
        at: '04:30:00'
    condition:
      - condition: state
        entity_id: group.people
        state: 'off'
      - condition: time
        before: '06:00:00'
    action:
      - service: input_boolean.turn_on
        entity_id:
         - input_boolean.holiday_mode
      - service: script.notify_away
        data:
          title: "\U0001F334 Holiday Mode"
          message: "Have a great time, guys!"
