# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:40
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 24/03/2018 18:14

# This package deals with making it a Secure and Stable flat ;) #Election2017

homeassistant:
  customize:
    binary_sensor.front_door_sensor:
      friendly_name: "Front Door"
      icon: mdi:exit-to-app

# Canary camera is exposed through the canary component
group:
  Canary:
    name: Canary
    control: hidden
    entities:
      - camera.living_room

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30

# There's a contact sensor on the front door which triggers if the door is opened.
sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {% if is_state('sensor.front_door_access_control', '22') %}
            Open
          {% else %}
            Closed
          {% endif %}

input_boolean:
  front_door:
    initial: off
    name: Front Door
    icon: mdi:exit-to-app
  front_door_recent:
    initial: off
    name: Front Door Recent
    icon: mdi:exit-to-app

automation:

  - alias: 'Lockdown'
    trigger:
         platform: state
         entity_id: group.people
         from: 'on'
         to: 'off'
    action:
        - service: light.turn_off
          entity_id: group.all_lights
        - service: alarm_control_panel.alarm_arm_away
          entity_id: alarm_control_panel.basecamp
        - service: script.notify_all
          data:
            title: "\U0001F512 Lockdown"
            message: "Everyone's Away - Everything is off and Canary is armed and ready!"
        - service: input_boolean.turn_off
          entity_id: input_boolean.home_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.away_mode
        - service: group.set_visibility
          entity_id: group.canary
          data:
            visible: true

  - alias: 'Front Door Opened'
    trigger:
        platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
    condition:
      - condition: state
        entity_id: input_boolean.front_door
        state: 'off'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door_recent # Designed to effectively reset the front-door timer if it's opened >3 mins <10 after the first opening.
      - service: input_boolean.turn_on
        entity_id: input_boolean.front_door
      - service: input_boolean.turn_on
        entity_id: input_boolean.front_door_recent
      # This notification was initially just for debugging but actually I've become accustomed to it!
      - service: notify.will
        data:
          title: "\U0001F6AA Door Open"
          message: "#SecureByDefault"

  # Another refractory period to stop repeated notifications if the door is opened and closed several times in a short period.
  - alias: 'Front Door Expiry'
    trigger:
        platform: state
        entity_id: input_boolean.front_door
        to: 'on'
        for:
          minutes: 3
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door

  - alias: 'Front Door Recent Expiry'
    trigger:
        platform: state
        entity_id: input_boolean.front_door_recent
        to: 'on'
        for:
          minutes: 10 # Might reduce this later
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door_recent

  # If people get back, turn off Canary, set the flat to home_mode and get rid of the lockdown notification.
  - alias: 'Occupied'
    trigger:
         platform: state
         entity_id: group.people
         from: 'off'
         to: 'on'
    action:
        - service: input_boolean.turn_off
          entity_id: input_boolean.away_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.home_mode
        - service: alarm_control_panel.alarm_disarm
          entity_id: alarm_control_panel.basecamp
        - service: persistent_notification.dismiss
          data:
            notification_id: "404"
        - service: group.set_visibility
          entity_id: group.canary
          data:
            visible: false

  - alias: Canary Hidden
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
        - service: group.set_visibility
          entity_id: group.canary
          data:
            visible: false

  # If at 04:30 everyone is away then automagically switch on holiday mode.
  - alias: 'Auto holiday mode'
    trigger:
        platform: time
        at: '04:30:00'
    condition:
      - condition: state
        entity_id: group.people
        state: 'off'
      - condition: time
        before: '06:00:00'
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id:
         - input_boolean.holiday_mode
      - service: script.notify_away
        data:
          title: "\U0001F334 Holiday Mode"
          message: "Have a great time, guys!"
