# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:40
# @Project: Ambassadr Home Automation
# @Last modified by:   willscottuk
# @Last modified time: 29/07/2017 15:06

# This package deals with making it a Secure and Stable flat ;) #Election2017

# This connects Canary to HASS. It's not pretty but it works! Shame there's no camera access.
wink:
  email: !secret wink_user
  password: !secret wink_pass
  client_id: !secret wink_id
  client_secret: !secret wink_secret

camera:
  - platform: mjpeg
    mjpeg_url: http://10.10.1.30:2971/camera/stream

automation:

  - alias: 'Lockdown'
    trigger:
         platform: state
         entity_id: group.people
         from: 'on'
         to: 'off'
    action:
        - service: light.turn_off
          entity_id: group.all_lights
        - service: alarm_control_panel.alarm_arm_away
          entity_id: alarm_control_panel.living_room
        - service: script.notify_all
          data:
            title: "\U0001F512 Lockdown"
            message: "Everyone's Away - Everything is off and Canary is armed and ready!"
        - service: input_boolean.turn_off
          entity_id: input_boolean.home_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.away_mode

  - alias: 'Occupied'
    trigger:
         platform: state
         entity_id: group.people
         from: 'off'
         to: 'on'
    action:
        - service: input_boolean.turn_off
          entity_id: input_boolean.away_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.home_mode
        - service: alarm_control_panel.alarm_disarm
          entity_id: alarm_control_panel.living_room

  - alias: 'Auto holiday mode'
    trigger:
        platform: time
        at: '04:30:00'
    condition:
      - condition: state
        entity_id: group.people
        state: 'off'
      - condition: time
        before: '06:00:00'
    action:
      - service: input_boolean.turn_on
        entity_id:
         - input_boolean.holiday_mode
      - service: script.notify_away
        data:
          title: "\U0001F334 Holiday Mode"
          message: "Have a great time, guys!"
