# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 20:40
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 21/01/2018 11:07

# This package deals with making it a Secure and Stable flat ;) #Election2017

homeassistant:
  customize:
    binary_sensor.front_door_sensor:
      friendly_name: "Front Door"
      icon: mdi:exit-to-app

# This is the camera stream from the tablet which may eventually be mounted in the hall!
camera:
  - platform: mjpeg
    mjpeg_url: http://10.10.1.30:2971/camera/stream

# There's a contact sensor on the front door which triggers if the door is opened.
sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {% if is_state('sensor.front_door_access_control', '23') %}
            Closed
          {% else %}
            Open
          {% endif %}

input_boolean:
  front_door:
    initial: off
    name: Front Door
    icon: mdi:exit-to-app

automation:

  - alias: 'Lockdown'
    trigger:
         platform: state
         entity_id: group.people
         from: 'on'
         to: 'off'
    action:
        - service: light.turn_off
          entity_id: group.all_lights
        - service: alarm_control_panel.alarm_arm_away
          entity_id: alarm_control_panel.basecamp
        - service: script.notify_all
          data:
            title: "\U0001F512 Lockdown"
            message: "Everyone's Away - Everything is off and Canary is armed and ready!"
        - service: input_boolean.turn_off
          entity_id: input_boolean.home_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.away_mode

  - alias: 'Front Door Opened'
    trigger:
        platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
    condition:
      - condition: state
        entity_id: input_boolean.front_door
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.front_door
      # This notification was initially just for debugging but actually I've become accustomed to it!
      - service: notify.will
        data:
          title: "\U0001F6AA Door Open"
          message: "#SecureByDefault"

  # Another refractory period to stop repeated notifications if the door is opened and closed several times in a short period.
  - alias: 'Front Door Expiry'
    trigger:
        platform: state
        entity_id: input_boolean.front_door
        to: 'on'
        for:
          minutes: 3
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door

  # If people get back, turn off Canary, set the flat to home_mode and get rid of the lockdown notification.
  - alias: 'Occupied'
    trigger:
         platform: state
         entity_id: group.people
         from: 'off'
         to: 'on'
    action:
        - service: input_boolean.turn_off
          entity_id: input_boolean.away_mode
        - service: input_boolean.turn_on
          entity_id: input_boolean.home_mode
        - service: alarm_control_panel.alarm_disarm
          entity_id: alarm_control_panel.basecamp
        - service: persistent_notification.dismiss
          data:
            notification_id: "404"

  # If at 04:30 everyone is away then automagically switch on holiday mode.
  - alias: 'Auto holiday mode'
    trigger:
        platform: time
        at: '04:30:00'
    condition:
      - condition: state
        entity_id: group.people
        state: 'off'
      - condition: time
        before: '06:00:00'
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id:
         - input_boolean.holiday_mode
      - service: script.notify_away
        data:
          title: "\U0001F334 Holiday Mode"
          message: "Have a great time, guys!"
