# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 19:10
# @Project: Ambassadr Home Automation
# @Last modified by:   willscottuk
# @Last modified time: 24/06/2017 23:02

# This package enables the evening light transitions
# @Dependencies: packages/lights, packages/presence


switch:
  - platform:  flux
    lights:
      - light.sofa
      - light.dining
      - light.main
      - light.will_side
      - light.daniel_side
      - light.utility
      - light.bathroom
      - light.map
    name: Flux
    start_time: '06:00'
    stop_time: '22:00'
    start_colortemp: 5000
    sunset_colortemp: 3500
    stop_colortemp: 2500
    mode: mired
    disable_brightness_adjust: true

# SCENES

scene:
  - name: Sunset1
    entities:
     group.living_room:
        state: on
        transition: 90
        brightness: 35
        color_temp: 285
  - name: Sunset2
    entities:
     group.living_room:
        state: on
        transition: 90
        brightness: 70
        color_temp: 285
  - name: Sunset3
    entities:
     group.living_room:
        state: on
        transition: 180
        brightness: 115
     group.hall:
        state: on
        transition: 10
        brightness: 25
     group.bedroom:
        state: on
        transition: 180
        brightness: 115



automation:
  - alias: 'Sunset Phase 1'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
    condition:
      condition: state
      entity_id: group.people
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.sunset1

  - alias: 'Sunset Phase 2'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 1.5
    condition:
      condition: state
      entity_id: group.people
      state: 'on'
    action:
        - service: scene.turn_on
          entity_id: scene.sunset2
        - service: light.turn_on
          entity_id: group.hall
          data:
            transition: 5
            brightness: 5
            color_temp: 285
        - delay: 00:00:01
        - service: light.turn_off
          entity_id: group.hall
        - delay: 00:00:02
        - service: light.turn_on
          entity_id: group.hall
          data:
            transition: 10
            brightness: 10
            color_temp: 285
        - delay: 00:00:01
        - service: light.turn_off
          entity_id: group.hall
        - delay: 00:00:02
        - service: light.turn_on
          entity_id: group.hall
          data:
            transition: 15
            brightness: 15
            color_temp: 285

  - alias: 'Sunset Phase 3'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -2.5
    condition:
        - condition: state
          entity_id: group.people
          state: 'on'
        - condition: time
          before: '22:00:00'
    action:
        - service: scene.turn_on
          entity_id: scene.sunset3
        - delay: 0:04
        - service: switch.turn_on
          entity_id: switch.flux

group:
  Flux:
    control: hidden
    entities:
      -  switch.flux
