# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 19:10
# @Project: Ambassadr Home Automation
# @Last modified by:   willscottuk
# @Last modified time: 02/07/2017 19:53

# This package enables the evening light transitions
# @Dependencies: packages/lights, packages/presence


switch:
  - platform:  flux
    lights:
      - light.sofa
      - light.dining
      - light.main
      - light.will_side
      - light.daniel_side
      - light.utility
      - light.bathroom
      - light.map
    name: Flux
    start_time: '06:00'
    stop_time: '22:00'
    start_colortemp: 5000
    sunset_colortemp: 3500
    stop_colortemp: 2500
    mode: mired
    disable_brightness_adjust: true


input_boolean:

# Comment: I know that these designations aren't actually astronomically accurate
# (see https://www.timeanddate.com/astronomy/different-types-twilight.html) but
# they're useful moderately descriptive terms for what I'm trying to acheive.

  early_twilight:
    initial: off
    name: Early Twilight

  mid_twilight:
    initial: off
    name: Mid Twilight

  dusk:
    initial: off
    name: Dusk

# SCENES

scene:
  - name: Sunset1
    entities:
     group.living_room:
        state: on
        transition: 90
        brightness: 35
        color_temp: 285
  - name: Sunset2
    entities:
     group.living_room:
        state: on
        transition: 90
        brightness: 70
        color_temp: 285
  - name: Sunset3
    entities:
     group.living_room:
        state: on
        transition: 180
        brightness: 115
     group.hall:
        state: on
        transition: 10
        brightness: 25
     group.bedroom:
        state: on
        transition: 180
        brightness: 115


# These are now just automations to turn on the switches. First set for clear(ish)
# skies, the second set for cloudy days...

automation:
  - alias: 'Early Twilight; Clear Skies'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
    condition:
      condition: state
      entity_id: sensor.dark_sky_cloud_coverage
      below: 60
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.early_twilight

  - alias: 'Mid Twilight; Clear Skies'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 1.5
    condition:
      condition: state
      entity_id: sensor.dark_sky_cloud_coverage
      below: 60
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.mid_twilight

  - alias: 'Dusk; Clear Skies'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -2.5
    condition:
      condition: state
      entity_id: sensor.dark_sky_cloud_coverage
      below: 60
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.dusk

# And now for cloudy skies

  - alias: 'Early Twilight; Clear Skies'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 5
    condition:
      condition: state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 60
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.early_twilight

  - alias: 'Mid Twilight; Clear Skies'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3
    condition:
      condition: state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 60
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.mid_twilight

  - alias: 'Dusk; Clear Skies'
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 0
    condition:
      condition: state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 60
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.dusk

group:
  Flux:
    control: hidden
    entities:
      -  switch.flux
