# @Author: Will Scott <willscottuk>
# @Date:   14/06/2017 21:13
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 19/01/2018 21:02

# This package deals with transport

homeassistant:
  customize:
    sensor.eastbound_trams:
      custom_ui_state_card: state-card-eastbound
    sensor.westbound_trams:
      custom_ui_state_card: state-card-westbound
    sensor.next_train_to_vic:
      custom_ui_state_card: state-card-traintimes
    sensor.tram_status:
      icon: mdi:tram

sensor:

  - platform: rest
    resource: https://api.tfl.gov.uk/line/tram/status
    name: Tram Status
    value_template: '{{value_json[0].lineStatuses[0].statusSeverityDescription}}'

# Add trams

  - platform: jsonrest
    name: Eastbound Trams
    resource: !secret eastbound_trams

  - platform: jsonrest
    name: Westbound Trams
    resource: !secret westbound_trams

  - platform: uk_transport
    app_id: !secret transport_id
    app_key: !secret transport_key
    queries:
      - mode: train
        origin: ECR
        destination: VIC
      - mode: train
        origin: ECR
        destination: CTK

  - platform: template
    sensors:
      # Deprecated sensors
      # eastbound_trams_next:
      #   friendly_name: 'East 1'
      #   value_template: '{{states.sensor.eastbound_trams.attributes.trams[0].destinationName}} - {{states.sensor.eastbound_trams.attributes.trams[0].timeToStationMin}}'
      # eastbound_trams_second:
      #   friendly_name: 'East 2'
      #   value_template: '{{states.sensor.eastbound_trams.attributes.trams[1].destinationName}} - {{states.sensor.eastbound_trams.attributes.trams[1].timeToStationMin}}'
      # westbound_trams_next:
      #   friendly_name: 'West 1'
      #   value_template: '{{states.sensor.westbound_trams.attributes.trams[0].destinationName}} - {{states.sensor.westbound_trams.attributes.trams[0].timeToStationMin}}'
      # westbound_trams_second:
      #   friendly_name: 'West 2'
      #   value_template: '{{states.sensor.westbound_trams.attributes.trams[1].destinationName}} - {{states.sensor.westbound_trams.attributes.trams[1].timeToStationMin}}'
      # next_train_vic_status:
      #   friendly_name: 'Next train status'
      #   value_template: '{{states.sensor.next_train_to_vic.attributes.next_trains[0].status}}'
      # next_train_vic_origin:
      #   friendly_name: 'Next train origin'
      #   value_template: '{{states.sensor.next_train_to_vic.attributes.next_trains[0].origin_name}}'
      # next_train_vic_estimated:
      #   friendly_name: 'Next train estimated'
      #   value_template: '{{states.sensor.next_train_to_vic.attributes.next_trains[0].estimated}}'
      # next_train_vic_scheduled:
      #   friendly_name: 'Next train scheduled'
      #   value_template: '{{states.sensor.next_train_to_vic.attributes.next_trains[0].scheduled}}'
      # next_train_vic_platform:
      #   friendly_name: 'Next train platform'
      #   value_template: '{{states.sensor.next_train_to_vic.attributes.next_trains[0].platform}}'
      next_train_ctk_status:
        friendly_name: 'Next train status'
        value_template: '{{states.sensor.next_train_to_ctk.attributes.next_trains[0].status}}'
      next_train_ctk_origin:
        friendly_name: 'Next train origin'
        value_template: '{{states.sensor.next_train_to_ctk.attributes.next_trains[0].origin_name}}'
      next_train_ctk_estimated:
        friendly_name: 'Next train estimated'
        value_template: '{{states.sensor.next_train_to_ctk.attributes.next_trains[0].estimated}}'
      next_train_ctk_scheduled:
        friendly_name: 'Next train scheduled'
        value_template: '{{states.sensor.next_train_to_ctk.attributes.next_trains[0].scheduled}}'
      next_train_ctk_platform:
        friendly_name: 'Next train platform'
        value_template: '{{states.sensor.next_train_to_ctk.attributes.next_trains[0].platform}}'

group:
  tram:
    name: Trams
    control: hidden
    entities:
      - sensor.tram_status
      - sensor.eastbound_trams
      - sensor.westbound_trams
  vic:
    name: VIC trains
    control: hidden
    entities:
      - sensor.next_train_to_vic
      # Deprecated sensors
      # - sensor.next_train_vic_status
      # - sensor.next_train_vic_origin
      # - sensor.next_train_vic_estimated
      # - sensor.next_train_vic_scheduled
      # - sensor.next_train_vic_platform
  ctk:
    name: CTK trains
    control: hidden
    entities:
      - sensor.next_train_ctk_status
      - sensor.next_train_ctk_origin
      - sensor.next_train_ctk_estimated
      - sensor.next_train_ctk_scheduled
      - sensor.next_train_ctk_platform

zone:
  - name: ECR
    latitude: 51.375561
    longitude: -0.092753
    radius: 190
    icon: mdi:train

automation:
  - alias: 'Will at ECR'
    trigger:
         platform: zone
         entity_id: device_tracker.will_iphone
         zone: zone.ecr
         event: enter
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: time
        before: '10:00:00'
      - condition: time
        after: '05:30:00'
    action:
        - service: notify.will
          data:
            title: "\U0001F689 Next 3 trains to VIC"
            message: "1: {{states.sensor.next_train_to_vic.attributes.next_trains[0].scheduled}} from {{states.sensor.next_train_to_vic.attributes.next_trains[0].origin_name}} is {{states.sensor.next_train_to_vic.attributes.next_trains[0].status | lower}}. Plat {{states.sensor.next_train_to_vic.attributes.next_trains[0].platform}} at {{states.sensor.next_train_to_vic.attributes.next_trains[0].estimated}}.
            2: {{states.sensor.next_train_to_vic.attributes.next_trains[1].scheduled}} from {{states.sensor.next_train_to_vic.attributes.next_trains[1].origin_name}} is {{states.sensor.next_train_to_vic.attributes.next_trains[1].status | lower}}. Plat {{states.sensor.next_train_to_vic.attributes.next_trains[1].platform}} at {{states.sensor.next_train_to_vic.attributes.next_trains[1].estimated}}.
            3: {{states.sensor.next_train_to_vic.attributes.next_trains[2].scheduled}} from {{states.sensor.next_train_to_vic.attributes.next_trains[2].origin_name}} is {{states.sensor.next_train_to_vic.attributes.next_trains[2].status | lower}}. Plat {{states.sensor.next_train_to_vic.attributes.next_trains[2].platform}} at {{states.sensor.next_train_to_vic.attributes.next_trains[2].estimated}}."

  - alias: 'Dan at ECR'
    trigger:
         platform: zone
         entity_id: device_tracker.dan_iphone
         zone: zone.ecr
         event: enter
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: time
        before: '10:00:00'
      - condition: time
        after: '05:30:00'
    action:
        - service: notify.will
          data:
            title: "\U0001F689 Next 3 trains to CTK"
            message: "1: {{states.sensor.next_train_to_ctk.attributes.next_trains[0].scheduled}} from {{states.sensor.next_train_to_ctk.attributes.next_trains[0].origin_name}} is {{states.sensor.next_train_to_ctk.attributes.next_trains[0].status | lower}}. Plat {{states.sensor.next_train_to_ctk.attributes.next_trains[0].platform}} at {{states.sensor.next_train_to_ctk.attributes.next_trains[0].estimated}}.
            2: {{states.sensor.next_train_to_ctk.attributes.next_trains[1].scheduled}} from {{states.sensor.next_train_to_ctk.attributes.next_trains[1].origin_name}} is {{states.sensor.next_train_to_ctk.attributes.next_trains[1].status | lower}}. Plat {{states.sensor.next_train_to_ctk.attributes.next_trains[1].platform}} at {{states.sensor.next_train_to_ctk.attributes.next_trains[1].estimated}}.
            3: {{states.sensor.next_train_to_ctk.attributes.next_trains[2].scheduled}} from {{states.sensor.next_train_to_ctk.attributes.next_trains[2].origin_name}} is {{states.sensor.next_train_to_ctk.attributes.next_trains[2].status | lower}}. Plat {{states.sensor.next_train_to_ctk.attributes.next_trains[2].platform}} at {{states.sensor.next_train_to_ctk.attributes.next_trains[2].estimated}}."
