# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 21:11
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 10/03/2018 10:07

# This package deals with frontend views

# TODO: Dynamic time of day views
#
# Ideas include a morning view with one touch control of lights, TV, curtains (in future), coffee (in future?) and displaying travel times quickly.
# For day / early afternoon there could be a focus on climate and energy efficiency.
# For late afternoon / evening it could be a focus on media & lighting
# For late evening / night it could be ways of gracefully winding down.

homeassistant:

  customize:
    light.living_room:
      icon: mdi:sofa
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider-toggle
      stretch_slider: true
    light.bedroom:
      icon: mdi:hotel
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider-toggle
    light.hall:
      icon: mdi:door-closed
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      stretch_slider: true
    light.map_room:
      icon: mdi:earth
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      stretch_slider: true
    light.bathroom:
      icon: mdi:hot-tub
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: single-line
      stretch_slider: true
    light.utility:
      icon: mdi:screwdriver
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: single-line
      stretch_slider: true
    light.kitchen:
      icon: mdi:fridge
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: hide-slider
      stretch_slider: true
    light.ensuite:
      icon: mdi:water-pump
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: hide-slider
      stretch_slider: true
    group.presence_sensors:
     friendly_name: "Presence"
    group.default_view:
     icon: mdi:home
    sensor.mode:
      icon: mdi:home-assistant
    sensor.living_room_tv_source:
      icon: mdi:home-automation
    alarm_control_panel.basecamp:
      icon: mdi:security-home
    sensor.front_door:
      icon: mdi:home-alert
    group.all_automations:
      hidden: false
    group.all_lights:
      hidden: false


sensor:
 - platform: template
   sensors:
     living_room_tv_source:
       value_template: >-
         {%- if states.media_player.livingroomtv.attributes["source"] is undefined -%}
           Off
         {%- elif states.media_player.livingroomtv.attributes["source"] == "LiveTV" -%}
           {{ states.media_player.livingroomtv.attributes["media_channel"] }}
         {%- else -%}
           {{ states.media_player.livingroomtv.attributes["source"] }}
         {%- endif -%}
       friendly_name: 'Living Room TV Source'
     mode:
       friendly_name: "Mode"
       value_template: >-
         {%- if is_state('input_boolean.holiday_mode', 'on') -%}
           Holiday
         {%- elif is_state('input_boolean.away_mode', 'on') -%}
           Away
         {%- elif is_state('input_boolean.quiet_mode', 'on') -%}
           Quiet
         {%- elif is_state('input_boolean.party_mode', 'on') -%}
           Party
         {%- elif is_state('input_boolean.guest_mode', 'on') -%}
           Guest
         {%- elif is_state('input_boolean.romance_mode', 'on') -%}
           Romance
         {%- elif is_state('input_select.time_mode', 'Night') -%}
           Night
         {%- elif is_state('input_select.time_mode', 'Evening') -%}
           Evening
         {%- elif is_state('input_select.time_mode', 'Afternoon') -%}
           Afternoon
         {%- elif is_state('input_select.time_mode', 'Morning') -%}
           Morning
         {%- elif is_state('input_select.time_mode', 'Dawn') -%}
           Dawn
         {%- elif is_state('input_boolean.home_mode', 'on') -%}
           Home
         {%- else -%}
           Unknown
         {%- endif -%}

group:
  default_view:
    name: Home
    icon: mdi:home
    view: yes
    entities:
      - group.ambassadr
      - group.canary
      - group.lights
      - group.internal
      - weather.dark_sky
      - group.plant_status

  Pulse:
    view: yes
    icon: mdi:pulse
    entities:
      - group.presence_sensors
      - group.power
      - group.speed
      - group.internal_details
      - group.system
      - group.plants
      - group.bloomsky
      - camera.cronx
      - group.climate

  Media:
    view: yes
    icon: mdi:cast
    entities:
      - group.living_room_media
      - group.spotify_card
      - group.playstation_4
      - group.sonos_livingroom
      - group.sonos_bedroom

  Transport:
    view: yes
    icon: mdi:train
    entities:
      - group.tram
      - group.vic
      - group.ctk

  Settings:
    icon: mdi:settings
    view: yes
    entities:
      - group.manual_modes
      - group.walarmclock
      - group.dalarmclock
      - group.all_automations
      - group.auto_modes
      - group.plant_switches
      - group.developer

  Ambassadr:
    - sensor.mode
    - sensor.living_room_tv_source
    - alarm_control_panel.basecamp
    - sensor.front_door

  Auto modes:
    - input_select.time_mode
    - input_select.sunset_phase
    - input_select.cloud_cover

automation:
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: ambassadr
