# @Author: Will Scott <willscottuk>
# @Date:   12/06/2017 21:11
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 21/01/2018 09:33

# This package deals with frontend views

# TODO: Dynamic time of day views
#
# Ideas include a morning view with one touch control of lights, TV, curtains (in future), coffee (in future?) and displaying travel times quickly.
# For day / early afternoon there could be a focus on climate and energy efficiency.
# For late afternoon / evening it could be a focus on media & lighting
# For late evening / night it could be ways of gracefully winding down.

homeassistant:

  customize:
    group.living_room:
     icon: mdi:sofa
    group.bedroom:
     icon: mdi:hotel
    group.hall:
     icon: mdi:exit-to-app
    group.map_room:
     icon: mdi:earth
    group.bathroom:
     icon: mdi:water-pump
    group.utility:
     icon: mdi:screwdriver
    group.kitchen:
      icon: mdi:food
    group.will_presence:
     friendly_name: "Presence"
    group.dan_presence:
     friendly_name: "Presence"
    group.default_view:
     icon: mdi:home
    group.all_automations:
      hidden: false
    group.all_lights:
      hidden: false


sensor:
 - platform: template
   sensors:
     living_room_tv_source:
       value_template: >-
         {%- if states.media_player.livingroomtv.attributes["source"] is undefined -%}
           Off
         {%- elif states.media_player.livingroomtv.attributes["source"] == "LiveTV" -%}
           {{ states.media_player.livingroomtv.attributes["media_channel"] }}
         {%- else -%}
           {{ states.media_player.livingroomtv.attributes["source"] }}
         {%- endif -%}
       friendly_name: 'Living Room TV Source'
     mode:
       friendly_name: "Mode"
       value_template: >-
         {%- if is_state('input_boolean.holiday_mode', 'on') -%}
           Holiday
         {%- elif is_state('input_boolean.away_mode', 'on') -%}
           Away
         {%- elif is_state('input_boolean.quiet_mode', 'on') -%}
           Quiet
         {%- elif is_state('input_boolean.party_mode', 'on') -%}
           Party
         {%- elif is_state('input_boolean.guest_mode', 'on') -%}
           Guest
         {%- elif is_state('input_boolean.romance_mode', 'on') -%}
           Romance
         {%- elif is_state('input_boolean.night_mode', 'on') -%}
           Night
         {%- elif is_state('input_boolean.evening_mode', 'on') -%}
           Evening
         {%- elif is_state('input_boolean.afternoon_mode', 'on') -%}
           Afternoon
         {%- elif is_state('input_boolean.morning_mode', 'on') -%}
           Morning
         {%- elif is_state('input_boolean.dawn_mode', 'on') -%}
           Dawn
         {%- elif is_state('input_boolean.home_mode', 'on') -%}
           Home
         {%- else -%}
           Unknown
         {%- endif -%}

group:
  default_view:
    name: Home
    icon: mdi:home
    view: yes
    entities:
      - group.ambassadr
      - group.lights
      - group.internal
      - weather.dark_sky
      - group.plant_status
      - group.living_room_media
      - group.spotify_card
      - group.playstation_4
      - group.vox_one

  Switches:
    icon: mdi:gesture-tap
    view: yes
    entities:
      - group.manual_modes
      - group.walarmclock
      - group.dalarmclock

  Pulse:
    view: yes
    icon: mdi:pulse
    entities:
      - group.presence_sensors
      - group.plants
      - group.power
      - group.speed
      - group.system
      - group.bloomsky
      - camera.cronx
      - group.climate

  Transport:
    view: yes
    icon: mdi:train
    entities:
      - group.tram
      - group.vic
      - group.ctk

  Settings:
    icon: mdi:settings
    view: yes
    entities:
      - group.scenes
      - group.flux
      - group.all_automations
      - group.time_modes

  Ambassadr:
    - sensor.mode
    - sensor.living_room_tv_source
    - alarm_control_panel.basecamp
    - sensor.front_door

automation:
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: ambassadr
